### ISSUE TITLE
Sharding-jdbc get different shardingValue between version 3.1.0 and version 2.0.3 when use a string type sharding column.

### ISSUE THREAD

**Issue by AlbertTao** [apache/incubator-shardingsphere#2101]
Use a string sharding column ,  suppose the sharding column value is "abcd";
When use sharding-jdbc 3.1.0 , found sharding value pass to ShardingStrategy.doSharding() was a integer value : -1 .
But use version 2.0.3 , the sharding value is original value ： "abcd"。

**Comment by codefairy08** [comment]
duplicate #1754

**Comment by AlbertTao** [comment]
@terrymanu I found the fix code, merge to version 3.1.0.1 .
 When will this version be released， does it has a certain time?

**Comment by terrymanu** [comment]
Please subscribe mail list, you can find the scheduler of release

**Comment by AlbertTao** [comment]
> Please subscribe mail list, you can find the scheduler of release

Thank you so much for your patience~

**Comment by AlbertTao** [comment]
@codefairy08 I just try with version 4.0.0.M1-SNAPSHOT , also get different with version 2.0.3.
version 2.0.3 get value "abcd" (4 chars）， but in version 4.0.0.M1-SNAPSHOT get value "'abcd'" (6chars)。

**Comment by codefairy08** [comment]
@AlbertTao  Please describe in detail, tell me where you get value "'abcd'" ?
two column value in condition are correct.the results are shown below。
![image](https://user-images.githubusercontent.com/39583929/55314185-2beb8f00-549c-11e9-90a8-5b811015ca25.png)
![image](https://user-images.githubusercontent.com/39583929/55314262-5ccbc400-549c-11e9-8a36-67e93753d936.png)

**Comment by AlbertTao** [comment]
Java code 

```java
        BufferedReader reader = new BufferedReader(new InputStreamReader(OrderTest.class
                .getResourceAsStream("/sharding-config-order-test.yaml"), "utf-8"));
        StringBuffer sb = new StringBuffer();
        CharBuffer charBuffer = CharBuffer.allocate(32);
        for (int count = reader.read(charBuffer); count > 0; count = reader.read(charBuffer)) {
            sb.append(charBuffer.flip());
        }

        DataSource dataSource = YamlShardingDataSourceFactory.createDataSource(sb.toString().getBytes("utf-8"));
        Connection connection = dataSource.getConnection();
        Statement st = connection.createStatement();
        ResultSet rs = st.executeQuery("select ts_order.* FROM ts_order where order_id='abcd'");
```
sharding-config-order-test.yaml config 
```yaml
dataSources:
  ds_0: !!com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test_d_1
    username: demo4
    password: demo135
    filters: stat
    initialSize: 2
    maxActive: 80
    maxWait: 5000
    testOnBorrow: true
    testOnReturn: true
    testWhileIdle: true
  ds_1: !!com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test_d_2
    username: demo4
    password: demo135
    filters: stat
    initialSize: 2
    maxActive: 80
    maxWait: 5000
    testOnBorrow: true
    testOnReturn: true
    testWhileIdle: true

shardingRule:
  tables:
    ts_order:
      actualDataNodes: ds_${0..1}.ts_order_0${1..2}
      databaseStrategy:
        inline:
          shardingColumn: order_id
          algorithmExpression: ds_${order_id.hashCode() % 2}
      tableStrategy:
        inline:
          shardingColumn: order_id
          algorithmExpression: ts_order_0${order_id.hashCode() % 2 + 1}
```
pom.xml dependency

```xml
        <dependency>
            <groupId>org.apache.shardingsphere</groupId>
            <artifactId>sharding-jdbc-core</artifactId>
            <version>4.0.0.M1-SNAPSHOT</version>
        </dependency>

        <dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>druid</artifactId>
            <version>1.0.9</version>
        </dependency>

        <dependency>
            <groupId>mysql</groupId>
            <artifactId>mysql-connector-java</artifactId>
            <version>5.1.36</version>
        </dependency>
```
