### ISSUE TITLE
support for SQL route extension

### ISSUE THREAD

**Issue by lalicw** [apache/incubator-shardingsphere#2158]
## Feature Request
we are using shardingsphere in our project, but we found there is no way to customize the sql route logic.

for example, there are only few tables using db sharding feature, so we don't want to parse the sql all the time,  and we can set some thread local context to tell the sharding-jdbc layer current sql wish to use db sharding or not. so we suggest to add the ability to add extension for sql route logic that can use the context to decide which datasource to be used without parsing the sql.

### Is your feature request related to a problem?
no
### Describe the feature you would like.
sql route extension ability without parse the sql.

**Comment by wgy8283335** [comment]
I'd like to take the issue. Which branch should I develop from, 4.0.0-RC1 ? @terrymanu

**Comment by wgy8283335** [comment]
@lalicw. Hi, my friend. Could you make a example of setting context to use few tables?
Beacuse, we could set tables which to use sharding currently. 
Parameters tables could configre only t_order and t_order_item will be sharded, as below:
```
dataSources:
  ds_0: !!org.apache.commons.dbcp.BasicDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo_ds_0
    username: root
    password:
  ds_1: !!org.apache.commons.dbcp.BasicDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo_ds_1
    username: root
    password:

shardingRule:  
  tables:
    t_order: 
      actualDataNodes: ds_${0..1}.t_order
      keyGeneratorColumnName: order_id
    t_order_item:
      actualDataNodes: ds_${0..1}.t_order_item
      keyGeneratorColumnName: order_item_id
```
