### ISSUE TITLE
Reconstruct API of EncryptRules

### ISSUE THREAD

**Issue by tristaZero** [apache/incubator-shardingsphere#2185]
After using encryptDataSource online, it is necessary to redesign the API of encryptRules. The final format of encryptConfiguration is as follows:

```
dataSource:  !!com.zaxxer.hikari.HikariDataSource
  driverClassName: com.mysql.jdbc.Driver
  jdbcUrl: jdbc:mysql://127.0.0.1:3306/demo_ds_0?serverTimezone=UTC&useSSL=false
  username: root
  password:
encryptRule:
  encryptors:
    defaultEncryptor:
      type: aes
      qualifiedColumns: t_encrypt.name
      props:
        aes.key.value: abc12345
```

```
shardingRule:
  tables:
    t_order:
      actualDataNodes: db${0..1}.t_order
      tableStrategy: 
        complex:
          shardingColumns: user_id, order_id
          algorithmClassName: org.apache.shardingsphere.core.parse.fixture.ComplexKeysShardingAlgorithmFixture
      logicIndex: order_index
    t_order_item:
      actualDataNodes: db${0..1}.t_order_item
      tableStrategy: 
        complex:
          shardingColumns: user_id, order_id, item_id
          algorithmClassName: org.apache.shardingsphere.core.parse.fixture.ComplexKeysShardingAlgorithmFixture 
      keyGenerator:
        type: SNOWFLAKE
        column: item_id
    t_place:
      actualDataNodes: db${0..1}.t_place
      tableStrategy: 
        complex:
          shardingColumns: user_new_id, guid
          algorithmClassName: org.apache.shardingsphere.core.parse.fixture.ComplexKeysShardingAlgorithmFixture
  bindingTables:
    - t_order, t_order_item
  encryptRule:
    encryptors:
      order_encryptor:
        type: aes
        qualifiedColumns: t_order.status
        props:
          aes.key.value: abc12345
```
