### ISSUE TITLE
Support Transparent Mode for Sharding-Proxy

### ISSUE THREAD

**Issue by tuohai666** [apache/incubator-shardingsphere#2189]
## Feature Request

**For English only**, other languages will not accept.

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot make decision by current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Is your feature request related to a problem?
No.
### Describe the feature you would like.
There are Sharding Mode and Master-Slave Mode in Sharding-Proxy for now. Each of them exits Rule in the config file. 
The Transparent Mode do not have a sharding rule or master-slave rule. In this mode, SQLs will be transported directly to the unique datasource. Config file like:

```
schemaName: demo_ds
dataSources:
  demo_ds:
    url: jdbc:mysql://127.0.0.1:3306/demo_ds?serverTimezone=UTC&useSSL=false
    username: root
    password:
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
```
The database client will operate demo_ds via Sharding-Proxy transparently benefit by the new Mode.
