### ISSUE TITLE
batch insert problem , use keyGeneratorColumnName

### ISSUE THREAD

**Issue by hebinzyz** [apache/incubator-shardingsphere#2197]
yaml database configure:

```yaml
    t_energy_heat: 
      keyGeneratorColumnName: id
      actualDataNodes: bmp.t_energy_heat
      databaseStrategy:
        none:
      tableStrategy: 
        none:
```

java：

```java
	@Insert("<script>insert into t_energy_heat (cid,MNum,aheat,acold,HPower,aflow,IV,IMPT,EMPT,TD,ZDFT,ZBWT,RTime,state,RT,HState) VALUES"
			+ "<foreach item='entity' index='index' collection='list' separator=','>"
			+"(#{entity.cid},#{entity.MNum},#{entity.aheat},#{entity.acold},#{entity.HPower},#{entity.aflow},#{entity.IV},#{entity.IMPT},#{entity.EMPT},#{entity.TD},#{entity.ZDFT},#{entity.ZBWT},#{entity.RTime},#{entity.state},#{entity.RT},#{entity.HState})"
			+ "</foreach></script>")
	int addBatchEnergyHeatData(@Param("list") List<EnergyHeatData> list);
```

problem
insert into t_energy_heat (cid,MNum,aheat,acold,HPower,aflow,IV,IMPT,EMPT,TD,ZDFT,ZBWT,RTime,state,RT,HState, id) VALUES  
 (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?), ?), 
 (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?), ?), 
 (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?), ?),
  (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?, ?)
