### ISSUE TITLE
sharding-proxy doesn't has some tables in the config default datasource,why?

### ISSUE THREAD

**Issue by tianyijushi** [apache/incubator-shardingsphere#2301]
## Question
i has three databases,the config-sharding.yaml like that :

```yaml
schemaName: sharding_db
dataSources:
  ds: 
    url: jdbc:mysql://******/dface_v3_base?serverTimezone=UTC&useSSL=false
    username: ****
    password: ****
    autoCommit: true
    connectionTimeout: 30000
    idleTimeout: 60000
    maxLifetime: 1800000
    maximumPoolSize: 50
  ds_0:
    url: jdbc:mysql://****/dface_v3_0?serverTimezone=UTC&useSSL=false
    username: ****
    password: ****
    autoCommit: true
    connectionTimeout: 30000
    idleTimeout: 60000
    maxLifetime: 1800000
    maximumPoolSize: 50
  ds_1:
    url: jdbc:mysql://****/dface_v3_1?serverTimezone=UTC&useSSL=false
    username: ****
    password: ****
    autoCommit: true
    connectionTimeout: 30000
    idleTimeout: 60000
    maxLifetime: 1800000
    maximumPoolSize: 50
shardingRule:
  tables:
    t_order:
      actualDataNodes: ds_${0..1}.t_order_${0..1}
      tableStrategy:
        inline:
          shardingColumn: order_id
          algorithmExpression: t_order_${order_id % 2}
      keyGeneratorColumnName: order_id
    t_order_item:
      actualDataNodes: ds_${0..1}.t_order_item_${0..1}
      tableStrategy:
        inline:
          shardingColumn: order_id
          algorithmExpression: t_order_item_${order_id % 2}
      keyGeneratorColumnName: order_item_id
  bindingTables:
    - t_order,t_order_item
  defaultDataSourceName: ds
  defaultDatabaseStrategy:
    inline:
      shardingColumn: user_id
      algorithmExpression: ds_${user_id % 2}
  defaultTableStrategy:
    none:
  defaultKeyGeneratorClassName: io.shardingsphere.core.keygen.DefaultKeyGenerator
```

The dface_v3_base has three tables:face_update,recurrence,t_config.
The dface_v3_0 has four tables:t_order_0,t_order_1,t_order_item_0,t_order_item_1.
The dface_v3_1 has four tables:t_order_0,t_order_1,t_order_item_0,t_order_item_1.

The question is :why the sharding-proxy just show four tables:recurrence,t_config,t_order,t_order_item
