### ISSUE TITLE
MasterSlaveDatasource and shardingDatasource could be used together in shardingproxy?

### ISSUE THREAD

**Issue by duanbin0414** [apache/incubator-shardingsphere#2397]
There is no such usage in the official example。version shardingProxy-4.0

**Comment by terrymanu** [comment]
MasterSlaveDatasource and shardingDatasource is used to Sharding-JDBC, there are no any relationship with Sharding-Proxy.

What do you want?

**Comment by duanbin0414** [comment]
> MasterSlaveDatasource and shardingDatasource is used to Sharding-JDBC, there are no any relationship with Sharding-Proxy.
> 
> What do you want?
Just like in sharding application, configure one that has both sharding and master-slave ability. In combination, the official examples are all used separately in proxy.

**Comment by terrymanu** [comment]
Can you take a look on the document?

**Comment by terrymanu** [comment]
FYI: https://shardingsphere.apache.org/document/current/en/manual/sharding-proxy/configuration/

Can you close this issue?

**Comment by huangdaxue** [comment]
I tried to follow this guide  https://shardingsphere.apache.org/document/current/en/manual/sharding-proxy/configuration/  ,but it does not work any more, an error 'IllegalArgumentException: Type is required' occurs,the version is 4.0.0-RC1，what does it mean ' type is required'?

**Comment by terrymanu** [comment]
Document should be update to new version

**Comment by tuohai666** [comment]
@huangdaxue I'll update the document later. Can you try to run shardingproxy according the conf files in shrding-proxy-bootstrap/src/main/resources/conf/*.yaml before I finish?

**Comment by huangdaxue** [comment]
@tuohai666 yeah，sharding, read_write split can work ,but https://shardingsphere.apache.org/document/current/en/manual/sharding-proxy/configuration/#data-sharding-read-write-split occurs error, i will wait for your document update,thank you

**Comment by tuohai666** [comment]
Don't need to wait the new document. Just configure by yourself instead of copy the expired document.

**Comment by tuohai666** [comment]
Try config as follow which will be updated in official website few days later.

### Data Sharding + Data Masking

dataSources:

```yaml
schemaName: sharding_db

dataSources:
  ds0: 
    url: jdbc:postgresql://localhost:5432/ds0
    username: root
    password: 
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 65
  ds1:
    url: jdbc:postgresql://localhost:5432/ds1
    username: root
    password: 
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 65

shardingRule:  
  tables:
    t_order: 
      actualDataNodes: ds${0..1}.t_order${0..1}
      tableStrategy: 
        inline:
          shardingColumn: order_id
          algorithmExpression: t_order${order_id % 2}
      keyGenerator:
        type: SNOWFLAKE
        columnn: order_id
    t_order_item:
      actualDataNodes: ds${0..1}.t_order_item${0..1}
      tableStrategy:
        inline:
          shardingColumn: order_id
          algorithmExpression: t_order_item${order_id % 2}
      keyGenerator:
        type: SNOWFLAKE
        columnn: order_item_id
  bindingTables:
    - t_order,t_order_item
  defaultDatabaseStrategy:
    inline:
      shardingColumn: user_id
      algorithmExpression: ds${user_id % 2}
  defaultTableStrategy:
    none:
    
  encryptRule:
    encryptors:
      order_encryptor:
        type: AES
        qualifiedColumns: t_order.order_id
        props:
          aes.key.value: 123456  
```
