### ISSUE TITLE
when select no rows,  sharding return   Cannot invoke method intdiv() on null object

### ISSUE THREAD

**Issue by thineagle** [apache/incubator-shardingsphere#2431]
version : 4.0.0-RC1 
table sharding rule
```
ass_attach:
      actualDataNodes: ds${0..1}.ass_attach
      databaseStrategy:
        inline:
          shardingColumn: inner_ac_id
          algorithmExpression: ds${inner_ac_id.intdiv(10000) % 2}
```
when we invoke select method , select * from table where column='1' , when the result is null , sharding return  Cannot invoke method intdiv() on null object.  how to fix it ?
