### ISSUE TITLE
can I dynamically configure actualDataNodes after the project started?

### ISSUE THREAD

**Issue by amnotare** [apache/incubator-shardingsphere#2645]
1. I use this version in my project.
```<dependency>
      <groupId>io.shardingsphere</groupId>
      <artifactId>sharding-jdbc-core</artifactId>
      <version>3.0.0</version>
    </dependency>
```
2. table structure
```
create table t_order
(
  f_id             bigint unsigned auto_increment comment 'id' primary key,
 ......
  f_created_at     timestamp(3)    default CURRENT_TIMESTAMP(3) not null comment '创建时间',
  f_updated_at     timestamp(3)    default CURRENT_TIMESTAMP(3) not null comment '更新时间'
```
  
Sharding column  is f_updated_at , one table per month.
can I update the actualDataNodes when my project already running instead of running my project again?

**Comment by terrymanu** [comment]
FYI: https://shardingsphere.apache.org/document/current/en/features/orchestration/config-center/

**Comment by amnotare** [comment]
```
dataSources:
  ds_0: !!com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.jdbc.Driver
    jdbcUrl: 'jdbc:mysql://localhost:3306/sharding_test?useSSL=false&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8'
    username: root
    password: 123456
    maximumPoolSize: 2

shardingRule:
  props:
    sql.show: true
  defaultDataSourceName: ds_0
  tables:
    t_order_archive:
      actualDataNodes: ds_0.t_order_2019_0${1..6}
      tableStrategy:
        standard:
          shardingColumn: f_created_at
          rangeAlgorithmClassName: com.test.sharding.OrderRangeShardingAlgorithm
          preciseAlgorithmClassName: com.test.sharding.OrderPreciseShardingAlgorithm
```
This is how I configure it and it works well.But there's a problem, if I published my project in 2019-06-30.By 2019-07-01, because t_order_2019_07 data node was not configured,so I have to reconfigure the actualDataNodes and publish the project again. Can I config the actualDataNodes dynamically without re-publishing the project.
