### ISSUE TITLE
Druid can't monitor when using Sharding-Jdbc

### ISSUE THREAD

**Issue by xiaolong7713** [apache/incubator-shardingsphere#2778]
### Which version of ShardingSphere did you use?
4.0.0-RC1

### Which project did you use? Sharding-JDBC or Sharding-Proxy?
Sharding-JDBC

Driud SQL monitor has not any thing,
![image](https://user-images.githubusercontent.com/26022132/62018687-53562c80-b1ee-11e9-9506-ea47a23adf71.png)

sharing-jdbc config:
``` yaml
shardingsphere:
    datasource:
      names: ds
      ds:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://xxx:3306/xxx?useSSL=false&useUnicode=true&characterEncoding=UTF-8
        username: root
        password: xxx
        druid:
          initialSize: 5
          minIdle: 5
          maxActive: 50
          maxWait: 60000
          timeBetweenEvictionRunsMillis: 60000
          minEvictableIdleTimeMillis: 30000
          validationQuery: SELECT 'x' FROM DUAL
          testWhileIdle: true
          testOnBorrow: false
          testOnReturn: false
          poolPreparedStatements: true
          maxPoolPreparedStatementPerConnectionSize: 20
          filters: stat,wall,slf4j
          connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000 
```

**Comment by terrymanu** [comment]
ShardingSphere facing to JDBC layer only, whatever the database connection pool is druid or other.
Monitor is not a JDBC protocol, so we don't know why it can not use.
Can you transfer this issue to druid's GitHub repo and try to analyze which JDBC protocol is not support first?

**Comment by xiaolong7713** [comment]
Thanks.

It works normal when I modified sharding-jdbc config:
```yaml
  shardingsphere:
    datasource:
      names: ds
      ds:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://172.31.53.4:3306/phonerobot-outbound?useSSL=false&useUnicode=true&characterEncoding=UTF-8
        username: root
        password: iflytek
        filters: stat,wall,slf4j
        druid:
          initialSize: 5
          minIdle: 5
          maxActive: 50
          maxWait: 60000
          timeBetweenEvictionRunsMillis: 60000
          minEvictableIdleTimeMillis: 30000
          validationQuery: SELECT 'x' FROM DUAL
          testWhileIdle: true
          testOnBorrow: false
          testOnReturn: false
          poolPreparedStatements: true
          maxPoolPreparedStatementPerConnectionSize: 20
          #filters: stat,wall,slf4j
          connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000   
```
