### ISSUE TITLE
How to config round robin routing of broadcast tables?

### ISSUE THREAD

**Issue by jeffmxzhao** [apache/incubator-shardingsphere#2791]
- sharding-jdbc-spring-boot-starter: 3.1.0
- Spring boot: 2.1.6.RELEASE
   

There is my application.yml
```yaml
sharding:
  jdbc:
    datasource:
      names: dnm1,dnm2,dns1,dns2
      dnm1:
        type: com.zaxxer.hikari.HikariDataSource
        driverClassName: com.mysql.jdbc.Driver
        jdbcUrl: jdbc:mysql://
        username: 
        password: 
      dnm2:
        type: com.zaxxer.hikari.HikariDataSource
        driverClassName: com.mysql.jdbc.Driver
        jdbcUrl: jdbc:mysql://
        username: 
        password: 
      dns1:
        type: com.zaxxer.hikari.HikariDataSource
        driverClassName: com.mysql.jdbc.Driver
        jdbcUrl: jdbc:mysql://
        username: 
        password: 
      dns2:
        type: com.zaxxer.hikari.HikariDataSource
        driverClassName: com.mysql.jdbc.Driver
        jdbcUrl: jdbc:mysql://
        username: 
        password: 
    config:
      sharding:
        master-slave-rules:
          test1:
            master-data-source-name: dnm1
            slave-data-source-names: dns1
          test2:
            master-data-source-name: dnm2
            slave-data-source-names: dns2         
        tables:       
          dict:
            actual-data-nodes: test$->{[1, 2]}.dict
            key-generator-column-name: id
        broadcast-tables:
          - dict
```
I configured `dict` as a broadcast table. It works good. But i found it always send query to the `test1` data node. How can i config broadcast table that the query can be send `test1` and `test2` randomly.
