### ISSUE TITLE
the latest 4.0.x version of the configuration MasterSlaveRuleConfiguration properly

### ISSUE THREAD

**Issue by lonyee1989** [apache/incubator-shardingsphere#2846]
The latest 4.0.x version of the configuration MasterSlaveRuleConfiguration properly

The hard solution by lonyee
[https://www.jianshu.com/p/30175084c918](https://www.jianshu.com/p/30175084c918)

It is best to modify the write related config class.

**Comment by lonyee1989** [comment]
for #2846 4.0.x version of the configuration MasterSlaveRuleConfiguration properly

**Comment by terrymanu** [comment]
We should update document later, but a full parameters' constructor is necessary.

I will open a new issue on document repo

**Comment by lonyee1989** [comment]
OK... I think custom yaml configuration should be supported, and does configuration validation work in the official yaml without parametric constructors?

like this? @terrymanu 
```
masterSlaveRules:
      ms_ds0:
        masterDataSourceName: ds0
        slaveDataSourceNames:
          - ds0_slave0
          - ds0_slave1
        loadBalanceAlgorithmType: ROUND_ROBIN
      ms_ds1:
        masterDataSourceName: ds1
        slaveDataSourceNames: 
          - ds1_slave0
          - ds1_slave1
        loadBalanceAlgorithmType: ROUND_ROBIN
```
