### ISSUE TITLE
encrypt not work in 4.0.0-RC2-SNAPSHOT version

### ISSUE THREAD

**Issue by jukai5501** [apache/incubator-shardingsphere#2866]
### Which version of ShardingSphere did you use?
4.0.0-RC2-SNAPSHOT

### Which project did you use? Sharding-JDBC or Sharding-Proxy?
Sharding-JDBC

### Expected behavior
Encrypt fields when inserting and decrypt fields when querying

### Actual behavior
Encrypt fields not work when inserting and decrypt fields not work when querying

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
```
spring: 
  shardingsphere:
    props:
      sql:
        show: true
    datasource:
      names: ds
      ds:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DB:test}?serverTimezone=Asia/Shanghai
        username: ${MYSQL_USER:test}
        password: ${MYSQL_PASSWORD:test}
        hikari:
          minimum-idle: 60
          maximum-pool-size: 60
          idle-timeout: 30000
          max-lifetime: 1800000
          connection-timeout: 30000
          pool-name: ExampleHikariCP
          connection-test-query: SELECT 1
    encrypt:
      tables:
        columns:
          encryptor: example_encrypt
          cipherColumn: user_auth.credential
          assistedQueryColumn: user_auth.credential
      encryptors:
        example_encrypt:
          type: aes
          props:
            'aes.key.value': ${SHARDING_ENCRYPTOR_AES_PWD:123456}
    sharding:
      tables:
        party:
          actual-data-nodes: ds.party_$->{0..1}
          key-generator:
            column: party_id
            type: snowflake
          table-strategy:
            inline:
              sharding-column: party_id
              algorithm-expression: party_$->{party_id % 2}
        user_auth:
          key-generator:
            column: user_auth_id
            type: snowflake
```

**Comment by KomachiSion** [comment]
@jukai5501, I think there are some mistakes in configuration.
And I want to make sure some information:

1. Do you want to encrypt table `user_auth` column `credential`?
2. Is table `user_auth` a sharding table?

**Comment by jukai5501** [comment]
Hi!
	1. Yes, I want to encrypt table user_auth column credential.
	2. Table user_auth is not a sharding table.

**Comment by KomachiSion** [comment]
Try to use this configuration:

```
spring: 
  shardingsphere:
    props:
      sql:
        show: true
    datasource:
      names: ds
      ds:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DB:test}?serverTimezone=Asia/Shanghai
        username: ${MYSQL_USER:test}
        password: ${MYSQL_PASSWORD:test}
        hikari:
          minimum-idle: 60
          maximum-pool-size: 60
          idle-timeout: 30000
          max-lifetime: 1800000
          connection-timeout: 30000
          pool-name: ExampleHikariCP
          connection-test-query: SELECT 1
    encrypt:
      tables:
        user_auth:
          columns:
            credential:
              encryptor: example_encrypt
              cipherColumn: credential
              assistedQueryColumn: credential_assisted
      encryptors:
        example_encrypt:
          type: aes
          props:
            'aes.key.value': ${SHARDING_ENCRYPTOR_AES_PWD:123456}
    sharding:
      tables:
        party:
          actual-data-nodes: ds.party_$->{0..1}
          key-generator:
            column: party_id
            type: snowflake
          table-strategy:
            inline:
              sharding-column: party_id
              algorithm-expression: party_$->{party_id % 2}
```

**Comment by jukai5501** [comment]
Hi!

	This configuration did not work.



	Failed to bind properties under 'spring.shardingsphere.encrypt.tables.userauth.columns.encryptor' to org.apache.shardingsphere.core.yaml.config.encrypt.YamlEncryptColumnRuleConfiguration: 

	 Property: spring.shardingsphere.encrypt.tables.userauth.columns.encryptor 
         Value: example_encrypt 
         Origin: class path resource [application.yml]:64:24 
         Reason: No converter found capable of converting from type [java.lang.String] to type [org.apache.shardingsphere.core.yaml.config.encrypt.YamlEncryptColumnRuleConfiguration]

**Comment by KomachiSion** [comment]
Are you using the latest 4.0.0-RC2-SNAPSHOT?

I execute the configuration without exception:

```
spring:
  shardingsphere:
    datasource:
      names: ds
      ds:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3306/demo_ds?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false
        username: root
        password:

    sharding:
      default-data-source-name: ds
      tables:
        party:
          actual-data-nodes: ds.party_$->{0..1}
          table-strategy:
            inline:
              sharding-column: party_id
              algorithm-expression: party_$->{party_id % 2}
          key-generator:
            column: party_id
            type: SNOWFLAKE
            props:
              worker.id: 1
              max.tolerate.time.difference.milliseconds: 100
    encrypt:
      tables:
        user_auth:
          columns:
            credential:
              encryptor: example_encrypt
              cipherColumn: credential
              assistedQueryColumn: credential
      encryptors:
        example_encrypt:
          type: aes
          props:
            'aes.key.value': 123456

    props:
      sql.show: true
```

**Comment by jukai5501** [comment]
Sorry, i am not using the latest 4.0.0-RC2-SNAPSHOT. 
I will pull the latest 4.0.0-RC2-SNAPSHOT branch and try it again.




------------------ 原始邮件 ------------------
发件人: "杨翊 Sion Yang"<notifications@github.com>;
发送时间: 2019年8月14日(星期三) 中午11:06
收件人: "apache/incubator-shardingsphere"<incubator-shardingsphere@noreply.github.com>;
抄送: "Huangyongjun"<305981646@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [apache/incubator-shardingsphere] encrypt not work in4.0.0-RC2-SNAPSHOT version (#2866)




Are you using the latest 4.0.0-RC2-SNAPSHOT?
 
I execute the configuration without exception:
 spring:   shardingsphere:     datasource:       names: ds       ds:         type: com.zaxxer.hikari.HikariDataSource         driver-class-name: com.mysql.jdbc.Driver         jdbc-url: jdbc:mysql://localhost:3306/demo_ds?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false         username: root         password:     sharding:       default-data-source-name: ds       tables:         party:           actual-data-nodes: ds.party_$->{0..1}           table-strategy:             inline:               sharding-column: party_id               algorithm-expression: party_$->{party_id % 2}           key-generator:             column: party_id             type: SNOWFLAKE             props:               worker.id: 1               max.tolerate.time.difference.milliseconds: 100     encrypt:       tables:         user_auth:           columns:             credential:               encryptor: example_encrypt               cipherColumn: credential               assistedQueryColumn: credential       encryptors:         example_encrypt:           type: aes           props:             'aes.key.value': 123456     props:       sql.show: true

**Comment by jukai5501** [comment]
Hi!

	I pulled the latest 4.0.0-RC2-SNAPSHOT version. The application can start normally, I was using your configuration, but the logs printed like this.

	```

	2019-08-14 22:29:27.376 INFO 39486 --- [ main] o.a.s.core.util.ConfigurationLogger : EncryptRuleConfiguration 
	encryptors: 
	  example_encrypt: 
            props: aes.key.value: 123456
            type: aes 
        tables: 
          user_auth: 
            columns: 
              credential: 
                assistedQueryColumn: credential 
                cipherColumn: credential 
                encryptor: example_encrypt 
         2019-08-14 22:29:27.377 INFO 39486 --- [ main] o.a.s.core.util.ConfigurationLogger : Properties 
         sql.show: ‘true'

	```

	Then there are not printing sharding configuration, but I configure them. 
	So sharding does not work when i call the query or save interface.

	```
	2019-08-14 22:30:47.712 INFO 39486 --- [ XNIO-1 task-1] ShardingSphere-SQL : SQL: insert into party (party_nickname, party_nickname_spelling, sex, birthday, personal_profile, status_cd, create_dt, update_dt, status_dt) values (?, ?, ?, ?, ?, ?, ?, ?, ?) 		 2019-08-14 22:30:47.798 ERROR 39486 --- [ XNIO-1 task-1] c.h.g.s.c.s.a.m.e.GlobalExceptionHandler : Internal exception: org.springframework.dao.DataIntegrityViolationException: ### Error updating database. Cause: java.sql.SQLException: Field 'party_id' doesn't have a default value

	```

**Comment by KomachiSion** [comment]
Do you set party_id as key_generator?
It looks like configuration error for `key-generator`

**Comment by jukai5501** [comment]
Hi!

	Yes, I set party_id as key_generator. This is my configuration.

```
spring:
  shardingsphere:
    props:
      sql:
        show: true
    datasource:
      names: ds
      ds:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DB:test}?serverTimezone=Asia/Shanghai
        username: ${MYSQL_USER:test}
        password: ${MYSQL_PASSWORD:test}
        hikari:
          minimum-idle: 60
          maximum-pool-size: 60
          idle-timeout: 30000
          max-lifetime: 1800000
          connection-timeout: 30000
          pool-name: ExampleHikariCP
          connection-test-query: SELECT 1
    encrypt:
      tables:
        user_auth:
          columns:
            credential:
              encryptor: example_encrypt
              cipherColumn: credential
              assistedQueryColumn: credential
      encryptors:
        example_encrypt:
          type: aes
          props:
            'aes.key.value': 123456
    sharding:
      default-data-source-name: ds
      tables:
        party:
          actual-data-nodes: ds.party_$->{0..1}
          key-generator:
            column: party_id
            type: snowflake
          table-strategy:
            inline:
              sharding-column: party_id
              algorithm-expression: party_$->{party_id % 2}
```

**Comment by KomachiSion** [comment]
Please change to this configuration and retry.

```
spring:
  shardingsphere:
    datasource:
      names: ds
      ds:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3306/demo_ds?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false
        username: root
        password:

    sharding:
      default-data-source-name: ds
      tables:
        party:
          actual-data-nodes: ds.party_$->{0..1}
          table-strategy:
            inline:
              sharding-column: party_id
              algorithm-expression: party_$->{party_id % 2}
          key-generator:
            column: party_id
            type: SNOWFLAKE
            props:
              worker.id: 1
              max.tolerate.time.difference.milliseconds: 100
      encrypt-rule:
        tables:
          user_auth:
            columns:
              credential:
                encryptor: example_encrypt
                cipherColumn: credential
                assistedQueryColumn: credential
        encryptors:
          example_encrypt:
            type: aes
            props:
              'aes.key.value': 123456

    props:
      sql.show: true
```
