### ISSUE TITLE
sharding didn't affect when using sharding and encrypt!(4.0.0-RC1 and 4.0.0-RC2)

### ISSUE THREAD

**Issue by yhsmy** [apache/incubator-shardingsphere#2924]
the profile as below:

spring:
&nbsp;&nbsp;shardingsphere:
    &nbsp;&nbsp;&nbsp;&nbsp;props:
      &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;sql.show: true
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;query.with.cipher.comlum: true
&nbsp;&nbsp;&nbsp;&nbsp;datasource:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;name: ds0
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;ds0:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;type: org.apache.commons.dbcp.BasicDataSource

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;driver-class-name: com.mysql.cj.jdbc.Driver

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;username: root

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;password: root

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;max-total: 100
&nbsp;&nbsp;&nbsp;&nbsp;sharding:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;tables:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;user:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;actual-data-nodes: ds0.user_$->{0..4}
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;table-strategy:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;inline:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;sharding-column: id
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;algorithm-expression: user_$->{id % 5}
&nbsp;&nbsp;&nbsp;&nbsp;encrypt:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;encryptors:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;encryptor_aes:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;type: aes
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;props.aes.key.value: 123456
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;tables:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;user:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;columns:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;name:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;cipherColumn: name
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;encryptor: encryptor_aes

**Comment by Keanhua** [comment]
i want use the read and write split and the encrypt but i found the column  is not decrypt successful

**Comment by sunbufu** [comment]
You can look at this <https://shardingsphere.apache.org/document/current/cn/manual/sharding-jdbc/configuration/config-yaml/>.

**Comment by yhsmy** [comment]
我就是按照这个写的。




On 08/29/2019 17:57, 孙不服 wrote:

You can look at this https://shardingsphere.apache.org/document/current/cn/manual/sharding-jdbc/configuration/config-yaml/.

**Comment by sunbufu** [comment]
```yml
spring:
  shardingsphere:
    props:
      sql.show: true
      query.with.cipher.comlum: true
    datasource:
      name: ds0
      ds0:
        type: org.apache.commons.dbcp.BasicDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
        username: root
        password: root
        max-total: 100
    sharding:
      tables:
        user:
          actual-data-nodes: ds0.user_$->{0..4}
          table-strategy:
            inline:
              sharding-column: id
              algorithm-expression: user_$->{id % 5}
      encrypt-rule:
        encryptors:
          encryptor_aes:
            type: aes
            props.aes.key.value: 123456
        tables:
          user:
            columns:
              name:
                cipherColumn: name
                encryptor: encryptor_aes
```
Try again with this. `encrypt-rule` must be `sharding`'s child node.
