### ISSUE TITLE
Show create table error

### ISSUE THREAD

**Issue by wowojyc** [apache/incubator-shardingsphere#2935]
## Question
My sharding-jdbc version is :4.0.0.RC2
My execute sql is :show create table tb_a;
The exception is ：
![image](https://user-images.githubusercontent.com/9378228/63776816-aec22a00-c914-11e9-84f0-53b2bbf007a5.png)

In my configuration, the tb_a is not sharding table.

I have found out that, this is because the route result is null

In the UnicastRouteEngine, the following code may return a RoutingResult just initialized with consturctor.

![image](https://user-images.githubusercontent.com/9378228/63776952-e630d680-c914-11e9-8087-9f625c870dec.png)

So, what can I do to fix this question?

**Comment by sunbufu** [comment]
Hello @wowojyc , thanks for your issue. As your say `tb_a` is not a sharding table. so `tb_a` is a encrypted table? Can you show some configuration?

**Comment by wowojyc** [comment]
> Hello @wowojyc , thanks for your issue. As your say `tb_a` is not a sharding table. so `tb_a` is a encrypted table? Can you show some configuration?

Hi, thank you for your reply.

In my configuration, tb_a is a common table no need sharding. But when I try 'show databases' command, the same exception happened.

**Comment by sunbufu** [comment]
I think It is different, 
1. `SHOW DATABASES`, `SHOW TABLES` can not run right on sharding-jdbc, cause sharding-jdbc can not return without actual sql, but we will implement it in future.
2. You will not execute sql with table which not config. But you can config table be a sharding table or config datasource be a default datasource.

**Comment by wowojyc** [comment]
I have read the issue or website about how to configuration default datasource for sharding jdbc, however I am still confused.
I think is is not only mean call ShardingRuleConfiguration.setDefaultDatasourceName method.

What else could I do ?  Could you give me some examples using raw java

**Comment by sunbufu** [comment]
I think user can only execute sql which target is logical table on SS. and SS should shield out the actual table. 
And you can get some examples in this [repository](https://github.com/apache/incubator-shardingsphere-example).

**Comment by wowojyc** [comment]
> I think user can only execute sql which target is logical table on SS. and SS should shield out the actual table.
> And you can get some examples in this [repository](https://github.com/apache/incubator-shardingsphere-example).

I have read the examples, but I just want to know the suggestion in the official website mean

 
![image](https://user-images.githubusercontent.com/9378228/63829836-2dfb4080-c99d-11e9-8da4-382622664302.png)

Is it only mean call method setDefaultDataSourceName or defualtSharding***Strategy?
Where should I get the defaultDataSourceName? In my spring Application Context?

**Comment by sunbufu** [comment]
If you want to config default datasource, you can see [here](https://shardingsphere.apache.org/document/current/en/manual/sharding-jdbc/configuration/config-spring-boot/).
```properties
spring.shardingsphere.sharding.default-data-source-name=ds
```
Why you want to get defaultDataSourceName? SS will route sql to default dataSource when can not find a sharding datasource.

**Comment by wowojyc** [comment]
In my application may exists many different datasource.

So you mean that, for example if the spring boot inject one datasource, but it has no name, I just know its database name is 'db_a'. Do you mean the sharding.default-data-source-name will be set db_a.

the datasource name is database name or datasource pool name ?

**Comment by sunbufu** [comment]
If you use sharding-jdbc, we will implement it in future.
If you use sharding-proxy, hope my configuration can help you.
```yml
schemaName: sharding_db

dataSources:
  ds_0:
    url: jdbc:mysql://xxx:xxx/test?serverTimezone=UTC&useSSL=false
    username: root
    password: xxx
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
  ds_1:
    url: jdbc:mysql://xxx:xxx/information_schema?serverTimezone=UTC&useSSL=false
    username: root
    password: xxx
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50

shardingRule:
  defaultDataSourceName: ds_0
```

**Comment by DongJigong** [comment]
@wowojyc ShardingSphere has many databases and table strategy, you could choose one of them. If you want to hint at a specified database, I think the hinting strategy would be a good choice.

**Comment by wowojyc** [comment]
> If you use sharding-jdbc, we will implement it in future.
> If you use sharding-proxy, hope my configuration can help you.
> 
> ```yaml
> schemaName: sharding_db
> 
> dataSources:
>   ds_0:
>     url: jdbc:mysql://xxx:xxx/test?serverTimezone=UTC&useSSL=false
>     username: root
>     password: xxx
>     connectionTimeoutMilliseconds: 30000
>     idleTimeoutMilliseconds: 60000
>     maxLifetimeMilliseconds: 1800000
>     maxPoolSize: 50
>   ds_1:
>     url: jdbc:mysql://xxx:xxx/information_schema?serverTimezone=UTC&useSSL=false
>     username: root
>     password: xxx
>     connectionTimeoutMilliseconds: 30000
>     idleTimeoutMilliseconds: 60000
>     maxLifetimeMilliseconds: 1800000
>     maxPoolSize: 50
> 
> shardingRule:
>   defaultDataSourceName: ds_0
> ```
Is it ok to use default datasource name same with the sharding datasource name?

**Comment by wowojyc** [comment]
> @wowojyc ShardingSphere has many databases and table strategy, you could choose one of them. If you want to hint at a specified database, I think the hinting strategy would be a good choice.

Yeah, maybe.

However, the datasources in my application may contain some table need sharding but other not. I want they both use the same datasource proxy created by sharding jdbc.

**Comment by sunbufu** [comment]
> sharding datasource name?

It's OK, `defaultDataSourceName`'s value must comes from `dataSource`.

**Comment by wowojyc** [comment]
> dataSource

dataSource name? do you mean the dataSourceMap' key when create sharding datasource?
![image](https://user-images.githubusercontent.com/9378228/63853118-78e07c80-c9cc-11e9-940e-304a48c5319d.png)

**Comment by sunbufu** [comment]
`defaultDataSourceName` can be assigned a dataSourceName what set a actual dataSource. Like `db_0`,`db_1` in this case.
```yml
schemaName: sharding_db

dataSources:
  ds_0:
    url: jdbc:mysql://xxx:xxx/test?serverTimezone=UTC&useSSL=false
    username: root
    password: xxx
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
  ds_1:
    url: jdbc:mysql://xxx:xxx/information_schema?serverTimezone=UTC&useSSL=false
    username: root
    password: xxx
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50

shardingRule:
  defaultDataSourceName: ds_0
```
