### ISSUE TITLE
The configuration of RegistryCenter, ConfigCenter,LeafCenter should be split apart or not?

### ISSUE THREAD

**Issue by wgy8283335** [apache/incubator-shardingsphere#3185]
## The configuration of RegistryCenter, ConfigCenter,LeafCenter should be split apart or not?
As we plan to split the Resgitry Center Interface into RegistryCenter, ConfigCenter,LeafCenter. So,configuration of RegistryCenter and ConfigCenter should be split apart or not? For example:
```
orchestration:
  name: test
  overwrite: true
  registry:
    type: TestRegistryCenter
    namespace: test_encrypt
    serverLists: localhost:3181
  config:
    type: TestRegistryCenter
    namespace: test_encrypt
    serverLists: localhost:3181
  leaf:
    type: TestRegistryCenter
    namespace: test_encrypt
    serverLists: localhost:3181
```

**Comment by terrymanu** [comment]
I prefer do not split reg center and config center if user use same component (eg. zookeeper). 
But we'd better support user use different components for reg center and config center (eg. eureka for reg center and apollo for config center).

So we need to talk about how to deal with the configuration of these 2 different scenarios.

**Comment by wgy8283335** [comment]
Below is the current configuration 
```
spring.shardingsphere.orchestration.name= #Orchestration instance name
spring.shardingsphere.orchestration.overwrite= #Whether to overwrite local configurations with registry center configurations; if it can, each initialization should refer to local configurations
spring.shardingsphere.orchestration.registry.type= #Registry center type. Example:zookeeper
spring.shardingsphere.orchestration.registry.server-lists= #The list of servers that connect to registry center, including IP and port number; use commas to separate
spring.shardingsphere.orchestration.registry.namespace= #Registry center namespace
spring.shardingsphere.orchestration.registry.digest= #The token that connects to the registry center; default means there is no need for authentication
spring.shardingsphere.orchestration.registry.operation-timeout-milliseconds= #The millisecond number for operation timeout; default value: 500 milliseconds
spring.shardingsphere.orchestration.registry.max-retries= #Maximum retry time after failing; default value: 3 times
spring.shardingsphere.orchestration.registry.retry-interval-milliseconds= #Interval time to retry; default value: 500 milliseconds
spring.shardingsphere.orchestration.registry.time-to-live-seconds= #Living time of temporary nodes; default value: 60 seconds
spring.shardingsphere.orchestration.registry.props= #Customize registry center props.
```
Below is the modified
```
spring.shardingsphere.orchestration.name= #Orchestration instance name
spring.shardingsphere.orchestration.overwrite= #Whether to overwrite local configurations with registry center configurations; if it can, each initialization should refer to local configurations
spring.shardingsphere.orchestration.type= # Example:mix-zookeeper,reg-zookeeper,conf-zookeeper
spring.shardingsphere.orchestration.server-lists= #The list of servers that connect to registry center, including IP and port number; use commas to separate
spring.shardingsphere.orchestration.namespace= #Registry center namespace
spring.shardingsphere.orchestration.digest= #The token that connects to the registry center; default means there is no need for authentication
spring.shardingsphere.orchestration.operation-timeout-milliseconds= #The millisecond number for operation timeout; default value: 500 milliseconds
spring.shardingsphere.orchestration.max-retries= #Maximum retry time after failing; default value: 3 times
spring.shardingsphere.orchestration.retry-interval-milliseconds= #Interval time to retry; default value: 500 milliseconds
spring.shardingsphere.orchestration.time-to-live-seconds= #Living time of temporary nodes; default value: 60 seconds
spring.shardingsphere.orchestration.props= #Customize registry center props.
```

**Comment by wgy8283335** [comment]
@huangjian888 .  Are you interested in this issue?

**Comment by huangjian888** [comment]
> @huangjian888 . Are you interested in this issue?

At present, I also find that there are such problems, but there is no good plan.Because users may use different types of registries and configuration centers

**Comment by sunbufu** [comment]
Hi, we got some conclusions, after the discussion. 
The new configuration in the plan is as follows.
```yml
spring:
    shardingsphere:
        orchestration:
            name: ''
            overwrite: ''
            registry:
                digest: ''
                max-retries: ''
                name: '#Orchestration instance name'
                namespace: ''
                operation-timeout-milliseconds: ''
                props: ''
                retry-interval-milliseconds: ''
                server-lists: ''
                time-to-live-seconds: ''
                type: '#Example:zookeeper,nacos,apollo'
            config:
                digest: ''
                max-retries: ''
                name: '#Orchestration instance name'
                namespace: ''
                operation-timeout-milliseconds: ''
                overwrite: ''
                props: ''
                retry-interval-milliseconds: ''
                server-lists: ''
                time-to-live-seconds: ''
                type: '#Example:zookeeper,nacos,apollo'
            leaf:
                digest: ''
                max-retries: ''
                name: '#Orchestration instance name'
                namespace: ''
                operation-timeout-milliseconds: ''
                props: ''
                retry-interval-milliseconds: ''
                server-lists: ''
                time-to-live-seconds: ''
                type: '#Example:zookeeper,nacos,apollo'
```
The old configuration is as follows.
```yml
spring:
    shardingsphere:
        orchestration:
            name: ''
            overwrite: ''
            registry:
                digest: ''
                max-retries: ''
                namespace: ''
                operation-timeout-milliseconds: ''
                props: ''
                retry-interval-milliseconds: ''
                server-lists: ''
                time-to-live-seconds: ''
                type: ''
                use-for: '#'
```

We hope that the new configuration can be compatible with the old configuration, but we do not want the configuration to be redundant. There are some of difficulties we get, can you give me some advice ?

1. For compatibility with old configuration, ConfigCenter and ConfigCenter must be optional. Can we use RegistryCenter to do the job of ConfigCenter or LeafCenter When user don't config ConfigCenter or LeafCenter ?

2. There are `orchestration`'s child `name` in old configuration. Can we keep the `orchestration.name` and add `orchestration.registry.name` `orchestration.config.name` `orchestration.leaf.name` ?

We're very confused about this, Looking forward to your advice.

**Comment by wgy8283335** [comment]
`overwrite` is only for config. `orchestration.overwrite` will be overlap?

**Comment by wgy8283335** [comment]
what about this? but `overwrite` is still redundant.
```
spring:
    shardingsphere:
        orchestration:
            name: ''
            overwrite: ''
            registry:
                digest: ''
                max-retries: ''
                name: '#Orchestration instance name'
                namespace: ''
                operation-timeout-milliseconds: ''
                props: ''
                retry-interval-milliseconds: ''
                server-lists: ''
                time-to-live-seconds: ''
                type: '#Example:zookeeper,nacos,apollo'
    config:  
        name: '' 
        overwrite: ''         
        center:
                digest: ''
                max-retries: ''
                name: '#Orchestration instance name'
                namespace: ''
                operation-timeout-milliseconds: ''
                overwrite: ''
                props: ''
                retry-interval-milliseconds: ''
                server-lists: ''
                time-to-live-seconds: ''
                type: '#Example:zookeeper,nacos,apollo'
    leaf:       
        name: ''     
        overwrite: ''
        center:
                digest: ''
                max-retries: ''
                name: '#Orchestration instance name'
                namespace: ''
                operation-timeout-milliseconds: ''
                props: ''
                retry-interval-milliseconds: ''
                server-lists: ''
                time-to-live-seconds: ''
                type: '#Example:zookeeper,nacos,apollo'
```

**Comment by dongzl** [comment]
```
spring:
    shardingsphere:
        orchestration:
            name: ''
            overwrite: ''
            registry:
                digest: ''
                max-retries: ''
                name: '#Orchestration instance name'
                namespace: ''
                operation-timeout-milliseconds: ''
                props: ''
                retry-interval-milliseconds: ''
                server-lists: ''
                time-to-live-seconds: ''
                type: '#Example:zookeeper,nacos,apollo'
        config:  
           name: '' 
           overwrite: ''
           digest: ''
           max-retries: ''
           name: '#Orchestration instance name'
           namespace: ''
           operation-timeout-milliseconds: ''
           overwrite: ''
           props: ''
           retry-interval-milliseconds: ''
           server-lists: ''
           time-to-live-seconds: ''
           type: '#Example:zookeeper,nacos,apollo'
        leaf:       
          name: ''     
          overwrite: ''
          digest: ''
          max-retries: ''
          name: '#Orchestration instance name'
          namespace: ''
          operation-timeout-milliseconds: ''
          props: ''
          retry-interval-milliseconds: ''
          server-lists: ''
          time-to-live-seconds: ''
          type: '#Example:zookeeper,nacos,apollo'
```
How about this? feel a little simple.

**Comment by huangjian888** [comment]
spring:
    shardingsphere:
        orchestration:
            name: ''
            overwrite: ''
            registry:
                digest: ''
                max-retries: ''
                name: '#Orchestration instance name'
                namespace: ''
                operation-timeout-milliseconds: ''
                props: ''
                retry-interval-milliseconds: ''
                server-lists: ''
                time-to-live-seconds: ''
                type: '#Example:zookeeper,nacos,apollo'
            config:
                digest: ''
                max-retries: ''
                name: '#Orchestration instance name'
                namespace: ''
                operation-timeout-milliseconds: ''
                overwrite: ''
                props: ''
                retry-interval-milliseconds: ''
                server-lists: ''
                time-to-live-seconds: ''
                type: '#Example:zookeeper,nacos,apollo'
            leaf:
                digest: ''
                max-retries: ''
                name: '#Orchestration instance name'
                namespace: ''
                operation-timeout-milliseconds: ''
                props: ''
                retry-interval-milliseconds: ''
                server-lists: ''
                time-to-live-seconds: ''
                type: '#Example:zookeeper,nacos,apollo'
This plan！
At present,ConfigCenter and LeafCenter must be optional.we use RegistryCenter to do the job of ConfigCenter or LeafCenter When user don't config ConfigCenter or LeafCenter .
In this way, there will be a problem,the functions that can be realized by zookeeper RegistryCenter , but Nacos RegistryCenter  can't realize such functions!

**Comment by huangjian888** [comment]
If the Nacos configuration center does not support some methods, can we throw exceptions directly? Then tell the user to configure the leafcenter？

**Comment by wgy8283335** [comment]
> spring:
> shardingsphere:
> orchestration:
> name: ''
> overwrite: ''
> registry:
> digest: ''
> max-retries: ''
> name: '#Orchestration instance name'
> namespace: ''
> operation-timeout-milliseconds: ''
> props: ''
> retry-interval-milliseconds: ''
> server-lists: ''
> time-to-live-seconds: ''
> type: '#Example:zookeeper,nacos,apollo'
> config:
> digest: ''
> max-retries: ''
> name: '#Orchestration instance name'
> namespace: ''
> operation-timeout-milliseconds: ''
> overwrite: ''
> props: ''
> retry-interval-milliseconds: ''
> server-lists: ''
> time-to-live-seconds: ''
> type: '#Example:zookeeper,nacos,apollo'
> leaf:
> digest: ''
> max-retries: ''
> name: '#Orchestration instance name'
> namespace: ''
> operation-timeout-milliseconds: ''
> props: ''
> retry-interval-milliseconds: ''
> server-lists: ''
> time-to-live-seconds: ''
> type: '#Example:zookeeper,nacos,apollo'
> This plan！
> At present,ConfigCenter and LeafCenter must be optional.we use RegistryCenter to do the job of ConfigCenter or LeafCenter When user don't config ConfigCenter or LeafCenter .
> In this way, there will be a problem,the functions that can be realized by zookeeper RegistryCenter , but Nacos RegistryCenter can't realize such functions!

which plan？

**Comment by wgy8283335** [comment]
> > spring:
> > shardingsphere:
> > orchestration:
> > name: ''
> > overwrite: ''
> > registry:
> > digest: ''
> > max-retries: ''
> > name: '#Orchestration instance name'
> > namespace: ''
> > operation-timeout-milliseconds: ''
> > props: ''
> > retry-interval-milliseconds: ''
> > server-lists: ''
> > time-to-live-seconds: ''
> > type: '#Example:zookeeper,nacos,apollo'
> > config:
> > digest: ''
> > max-retries: ''
> > name: '#Orchestration instance name'
> > namespace: ''
> > operation-timeout-milliseconds: ''
> > overwrite: ''
> > props: ''
> > retry-interval-milliseconds: ''
> > server-lists: ''
> > time-to-live-seconds: ''
> > type: '#Example:zookeeper,nacos,apollo'
> > leaf:
> > digest: ''
> > max-retries: ''
> > name: '#Orchestration instance name'
> > namespace: ''
> > operation-timeout-milliseconds: ''
> > props: ''
> > retry-interval-milliseconds: ''
> > server-lists: ''
> > time-to-live-seconds: ''
> > type: '#Example:zookeeper,nacos,apollo'
> > This plan！
> > At present,ConfigCenter and LeafCenter must be optional.we use RegistryCenter to do the job of ConfigCenter or LeafCenter When user don't config ConfigCenter or LeafCenter .
> > In this way, there will be a problem,the functions that can be realized by zookeeper RegistryCenter , but Nacos RegistryCenter can't realize such functions!
> 
> which plan？ @huangjian888

**Comment by huangjian888** [comment]
> > > spring:
> > > shardingsphere:
> > > orchestration:
> > > name: ''
> > > overwrite: ''
> > > registry:
> > > digest: ''
> > > max-retries: ''
> > > name: '#Orchestration instance name'
> > > namespace: ''
> > > operation-timeout-milliseconds: ''
> > > props: ''
> > > retry-interval-milliseconds: ''
> > > server-lists: ''
> > > time-to-live-seconds: ''
> > > type: '#Example:zookeeper,nacos,apollo'
> > > config:
> > > digest: ''
> > > max-retries: ''
> > > name: '#Orchestration instance name'
> > > namespace: ''
> > > operation-timeout-milliseconds: ''
> > > overwrite: ''
> > > props: ''
> > > retry-interval-milliseconds: ''
> > > server-lists: ''
> > > time-to-live-seconds: ''
> > > type: '#Example:zookeeper,nacos,apollo'
> > > leaf:
> > > digest: ''
> > > max-retries: ''
> > > name: '#Orchestration instance name'
> > > namespace: ''
> > > operation-timeout-milliseconds: ''
> > > props: ''
> > > retry-interval-milliseconds: ''
> > > server-lists: ''
> > > time-to-live-seconds: ''
> > > type: '#Example:zookeeper,nacos,apollo'
> > > This plan！
> > > At present,ConfigCenter and LeafCenter must be optional.we use RegistryCenter to do the job of ConfigCenter or LeafCenter When user don't config ConfigCenter or LeafCenter .
> > > In this way, there will be a problem,the functions that can be realized by zookeeper RegistryCenter , but Nacos RegistryCenter can't realize such functions!
> > 
> > 
> > which plan？ @huangjian888

`spring:
    shardingsphere:
        orchestration:
            name: ''
            overwrite: ''
            registry:
                digest: ''
                max-retries: ''
                name: '#Orchestration instance name'
                namespace: ''
                operation-timeout-milliseconds: ''
                props: ''
                retry-interval-milliseconds: ''
                server-lists: ''
                time-to-live-seconds: ''
                type: '#Example:zookeeper,nacos,apollo'
            config:
                digest: ''
                max-retries: ''
                name: '#Orchestration instance name'
                namespace: ''
                operation-timeout-milliseconds: ''
                overwrite: ''
                props: ''
                retry-interval-milliseconds: ''
                server-lists: ''
                time-to-live-seconds: ''
                type: '#Example:zookeeper,nacos,apollo'
            leaf:
                digest: ''
                max-retries: ''
                name: '#Orchestration instance name'
                namespace: ''
                operation-timeout-milliseconds: ''
                props: ''
                retry-interval-milliseconds: ''
                server-lists: ''
                time-to-live-seconds: ''
                type: '#Example:zookeeper,nacos,apollo'`
@sunbufu This plan！
In this case, we need to consider the registry in different implementations。
such as,zookeeper configuration center support some methods,but Nacos configuration center does not support some methods,So, do we need to actively throw exceptions？Then tell the user to configure the leafcenter？

**Comment by wgy8283335** [comment]
@huangjian888 . The method of registry center, config center and leaf center will be slimed.

**Comment by huangjian888** [comment]
> @huangjian888 . The method of registry center, config center and leaf center will be slimed.

Do you have a good plan？how to split it？

**Comment by wgy8283335** [comment]
ConfigCenter（配置管理） | RegistryCenter（编排治理） | LeafCenter（Leaf主键生成）
-- | -- | --
void init(ConfigCenterConfiguration config); | void init(RegistryCenterConfiguration config); | void init(LeafCenterConfiguration config);
String get(String key); | String get(String key); | String get(String key);
  |   |  
  |   |  
List<String> getChildrenKeys(String key); | List<String> getChildrenKeys(String key); |  
void persist(String key, String value); | void persist(String key, String value); | void persist(String key, String value);
  |   |  
  | void persistEphemeral(String key, String value); |  
void watch(String key, DataChangedEventListener dataChangedEventListener); | void watch(String key, DataChangedEventListener dataChangedEventListener); |  
void close(); | void close(); |  
  |   | void initLock(String key);
  |   | boolean tryLock();
  |   | void tryRelease();
  |   |

**Comment by huangjian888** [comment]
> ConfigCenter（配置管理）	RegistryCenter（编排治理）	LeafCenter（Leaf主键生成）
> void init(ConfigCenterConfiguration config);	void init(RegistryCenterConfiguration config);	void init(LeafCenterConfiguration config);
> String get(String key);	String get(String key);	String get(String key);
>  	 	 
>  	 	 
> List getChildrenKeys(String key);	List getChildrenKeys(String key);	 
> void persist(String key, String value);	void persist(String key, String value);	void persist(String key, String value);
>  	 	 
>  	void persistEphemeral(String key, String value);	 
> void watch(String key, DataChangedEventListener dataChangedEventListener);	void watch(String key, DataChangedEventListener dataChangedEventListener);	 
> void close();	void close();	 
>  	 	void initLock(String key);
>  	 	boolean tryLock();
>  	 	void tryRelease();
>  	 	 
> @huangjian888

Big changes！And not compatible with older versions。But the plan is good！It may take more time to test。

**Comment by dongzl** [comment]
Hi @huangjian888
dzllikelsw@163.com this is my email, you can send your WeChat's account to this email, and we can friend each other.

**Comment by wgy8283335** [comment]
After discussion, the configuration will like this:
```
spring:
    shardingsphere:
        orchestration:
            testname1:
                center-type: registry_center,leaf_center
                instance-type: zookeeper
                server-lists: 192.178.32.45:9001,192.178.32.45:9002,192.178.32.45:9003
                namespace: testnamspace1
                props: 
		  overwrite: false
                  retry-interval-milliseconds: 10
                  time-to-live-seconds: 10
                  max-retries: 10
                  operation-timeout-milliseconds: 10
                  digest: 
            testname2:
                center-type: configuration_center
                instance-type: apollo
                server-lists: 192.178.32.45:9001,192.178.32.45:9002,192.178.32.45:9003
                namespace: testnamspace2
                props: 
                  overwrite: true
                  retry-interval-milliseconds: 10
                  time-to-live-seconds: 10
                  max-retries: 10
                  operation-timeout-milliseconds: 10
                  digest: 
```

**Comment by wgy8283335** [comment]
1. First Step
- modify sharding-orchestration-config, includes: interfaces, configuration, implementation.
- add sharding-orchestration-distributed-lock, includes: interfaces, configuration, implementation.
- modify sharding-orchestration-reg, include: configuration.and modify sharding-orchestration-core, include: initialization related.

2. Second Step
- add sharding-orchestration-instance. This module is for the implementation of reg, lock, config.
- modify sharding-orchestration-reg and delete implementations.
- sharding-orchestration-core modify initialization related.

3. Third Step
- modify registry center interface
- modify caller with config.
- modify caller with distributed lock.
- modify caller with reg. 
- sharding-orchestration-core modify initialization related.

**Comment by huangjian888** [comment]
> 1. First Step
> 
> * modify sharding-orchestration-config, includes: interfaces, configuration, implementation.
> * add sharding-orchestration-distributed-lock, includes: interfaces, configuration, implementation.
> * modify sharding-orchestration-reg, include: configuration.and modify sharding-orchestration-core, include: initialization related.
> 
> 1. Second Step
> 
> * add sharding-orchestration-instance. This module is for the implementation of reg, lock, config.
> * modify sharding-orchestration-reg and delete implementations.
> * sharding-orchestration-core modify initialization related.
> 
> 1. Third Step
> 
> * modify registry center interface
> * modify caller with config.
> * modify caller with distributed lock.
> * modify caller with reg.
> * sharding-orchestration-core modify initialization related.

sharding-orchestration-instance is it necessary?why?

**Comment by wgy8283335** [comment]
@huangjian888  Hi, you could clone branch orchestration 5.x. We have started. The 'sharding-orchestration-instance' module is not necessary, as I put implementation classes in the sharding-orchestration-center module. And are you still interested in this? Nacos implementation class is still need someone to write in sharding-orchestration-center module.

**Comment by huangjian888** [comment]
> @huangjian888 Hi, you could clone branch orchestration 5.x. We have started. The 'sharding-orchestration-instance' module is not necessary, as I put implementation classes in the sharding-orchestration-center module. And are you still interested in this? Nacos implementation class is still need someone to write in sharding-orchestration-center module.

Thanks for contributing！

**Comment by wgy8283335** [comment]
The new configuration in a yml file, will like this:
spring:
    shardingsphere:
        orchestration:
            testname1:
                orchestration-type: registry_center,distributed_lock_management
                instance-type: zookeeper
                server-lists: 192.178.32.45:9001,192.178.32.45:9002,192.178.32.45:9003
                namespace: testnamspace1
                props: 
		  overwrite: false
                  retry-interval-milliseconds: 10
                  time-to-live-seconds: 10
                  max-retries: 10
                  operation-timeout-milliseconds: 10
                  digest: 
            testname2:
                orchestration-type: configuration_center
                instance-type: apollo
                server-lists: 192.178.32.45:9001,192.178.32.45:9002,192.178.32.45:9003
                namespace: testnamspace2
                props: 
                  overwrite: true
                  retry-interval-milliseconds: 10
                  time-to-live-seconds: 10
                  max-retries: 10
                  operation-timeout-milliseconds: 10
                  digest:

**Comment by wgy8283335** [comment]
I'd like to modfiy yml file, as below:
```
spring:
    shardingsphere:
        orchestration:
            list:
            -
                orchestrationType: registry_center,distributed_lock_management
                instanceType: zookeeper
                serverLists: 192.178.32.45:9001,192.178.32.45:9002,192.178.32.45:9003
                namespace: testnamspace1
                props: 
		  overwrite: false
                  retryIntervalMilliseconds: 10
                  timeToLiveSeconds: 10
                  maxRetries: 10
                  operationTimeoutMilliseconds: 10
                  digest: 
            -
                orchestrationType: configuration_center
                instanceType: apollo
                serverLists: 192.178.32.45:9001,192.178.32.45:9002,192.178.32.45:9003
                namespace: testnamspace2
                props: 
		  overwrite: false
                  retryIntervalMilliseconds: 10
                  timeToLiveSeconds: 10
                  maxRetries: 10
                  operationTimeoutMilliseconds: 10
                  digest: 
```

**Comment by dongzl** [comment]
@wgy8283335 , if only one, e.g only ZookKeeper as `registry_center`, `distributed_lock_management` and `configuration_center`.

The yaml file is 
```
spring:
    shardingsphere:
        orchestration:
            list:
                orchestrationType: registry_center,distributed_lock_management,configuration_center
                instanceType: zookeeper
                serverLists: 192.178.32.45:9001,192.178.32.45:9002,192.178.32.45:9003
                namespace: testnamspace1
                props: 
		  overwrite: false
                   retryIntervalMilliseconds: 10
                   timeToLiveSeconds: 10
                   maxRetries: 10
                   operationTimeoutMilliseconds: 10
                   digest: 
```
Have I understood correctly?

**Comment by wgy8283335** [comment]
“-” should be kept.
```
spring:
    shardingsphere:
        orchestration:
            list:
              -  
                orchestrationType: registry_center,distributed_lock_management,configuration_center
                instanceType: zookeeper
                serverLists: 192.178.32.45:9001,192.178.32.45:9002,192.178.32.45:9003
                namespace: testnamspace1
                props: 
		  overwrite: false
                   retryIntervalMilliseconds: 10
                   timeToLiveSeconds: 10
                   maxRetries: 10
                   operationTimeoutMilliseconds: 10
                   digest: 
```
