### ISSUE TITLE
[sharding-jdbc-spring-boot-starter] wrong config key

### ISSUE THREAD

**Issue by spawpaw** [apache/incubator-shardingsphere#3441]
### Which project did you use? Sharding-JDBC or Sharding-Proxy?
I'm using sharding-jdbc v4.0.0-RC2:

```xml
        <dependency>
            <groupId>org.apache.shardingsphere</groupId>
            <artifactId>sharding-jdbc-spring-boot-starter</artifactId>
            <version>4.0.0-RC2</version>
        </dependency>
```
#### the doc uses `username` for ds config
![图片](https://user-images.githubusercontent.com/18007922/68102587-5f990680-ff0e-11e9-91b4-9ce4a94e23c8.png)

#### but it raises an error that username is empty:
![图片](https://user-images.githubusercontent.com/18007922/68102485-ed282680-ff0d-11e9-8ceb-ad2a0831a950.png)

#### problem is fixed when we chage the `username` to `name`
![图片](https://user-images.githubusercontent.com/18007922/68102573-527c1780-ff0e-11e9-9977-97a0f318f680.png)

### Expected behavior
the config key in `sharding-jdbc-spring-boot-starter` should be `username` or the config key in doc should be `user`

### Reason analyze (If you can)
typo

**Comment by spawpaw** [comment]
ummmmmm, i know why i have this problem...  
the config is different between datasource types, so...

for example, when I use hikari datasource, this config is ok:
```yaml
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3306/xxx
        username: root
        password: 123456
```
