### ISSUE TITLE
Inaccurate result when execute `desc encrypt_table`

### ISSUE THREAD

**Issue by tristaZero** [apache/incubator-shardingsphere#3639]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/incubator-shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
4.0.0-RC3
### Which project did you use? Sharding-JDBC or Sharding-Proxy?
Sharding-Proxy
### Expected behavior
Here is the configuration,
```
schemaName: encrypt_db

dataSource:
  url: jdbc:mysql://127.0.0.1:3306/demo_ds?serverTimezone=UTC&useSSL=false
  username: root
  password:
  connectionTimeoutMilliseconds: 30000
  idleTimeoutMilliseconds: 60000
  maxLifetimeMilliseconds: 1800000
  maxPoolSize: 50

encryptRule:
  encryptors:
    encryptor_aes:
      type: aes
      props:
        aes.key.value: 123456abc
    encryptor_md5:
      type: md5
  tables:
    t_encrypt:
      columns:
        user_id:
          plainColumn: user_plain
          cipherColumn: user_cipher
          encryptor: encryptor_aes
        order_id:
          cipherColumn: order_cipher
          encryptor: encryptor_md5
```

When execute `desc t_encrypt;`, expected result is 
```
mysql> desc t_encrypt;
+--------------+--------------+------+------+---------+----------------+
| Field        | Type         | Null | Key  | Default | Extra          |
+--------------+--------------+------+------+---------+----------------+
| id           | int(11)      | NO   | PRI  | NULL    | auto_increment |
| user_id  | varchar(200) | YES  |      | NULL    |                |
| order_id | varchar(200) | YES  |      | NULL    |                |
+--------------+--------------+------+------+---------+----------------+
```
### Actual behavior
```
mysql> desc t_encrypt;
+--------------+--------------+------+------+---------+----------------+
| Field        | Type         | Null | Key  | Default | Extra          |
+--------------+--------------+------+------+---------+----------------+
| id           | int(11)      | NO   | PRI  | NULL    | auto_increment |
| user_plain   | varchar(200) | YES  |      | NULL    |                |
| user_cipher  | varchar(200) | YES  |      | NULL    |                |
| order_cipher | varchar(200) | YES  |      | NULL    |                |
+--------------+--------------+------+------+---------+----------------+
```
