### ISSUE TITLE
Insert miss the plain columns in the final sql.

### ISSUE THREAD

**Issue by xiyelife** [apache/incubator-shardingsphere#3770]
### Which version of ShardingSphere did you use?
4.0.0-RC4-SNAPSHOT
### Which project did you use? Sharding-JDBC or Sharding-Proxy?
sharding-jdbc
### Expected behavior
the encrypt rule config  plain column  the same to logic column can insert plain column to the db
### Actual behavior
It can not insert the plain to the db
### Reason analyze (If you can)

org.apache.shardingsphere.sql.rewriter.encrypt.token.generator.impl.AssistQueryAndPlainInsertColumnsTokenGenerator#getColumns
![image](https://user-images.githubusercontent.com/8772975/71158965-d2243280-227f-11ea-8775-bec584488673.png)
This code cause the plain column can not be the same to the logic column，ohterwise the plain column is missing.

org.apache.shardingsphere.sql.rewriter.encrypt.parameter.impl.EncryptInsertValueParameterRewriter#encryptInsertValue：
**And  miss the plain column's parameter too：**
because of the logic column is the same to the plain column，it's only add the cipher column 
 for addReplacedParameters. (the plainColumnIndex must be not -1 when the logic column is the same to plain column)
![image](https://user-images.githubusercontent.com/8772975/71166227-35689180-228d-11ea-845b-46b5ae5c11fe.png)

rule config like this , the final sql will do not contains the plain columns! 

```
encryptRule:
  tables:
    t_account_bak:
      columns:
        password:
          cipherColumn: cipher_password
          assistedQueryColumn: assisted_query_password
          plainColumn: password
          encryptor: assisted_query
  encryptors:
    normal:
      type: NORMAL_ENCRYPT
    assisted_query:
      type: ASSISTED_QUERY_ENCRYPT
```

@terrymanu
