### ISSUE TITLE
Support for columns that only for routing

### ISSUE THREAD

**Issue by spawpaw** [apache/incubator-shardingsphere#3832]
For a simple logic delete scenario, assuming that we have a table split into 2 physical tables:

table:
```
order:
    - id
    - ...

order_deleted:
    - id
    - ...
```

## Current behaviour

Configuration:
```yml
dataSources:
  ds0: ...
shardingRule:  
  tables:
    t_order: 
      actualDataNodes: ds0.t_order, ds0.t_order_deleted
      tableStrategy: 
        inline:
          shardingColumn: order_id
          algorithmExpression: t_order${deleted?'_deleted':''}
```

SQLs before rewrite:
```sql
select * from t_order where deleted=0 and id>10 limit 100;
insert into t_order(id, deleted, ...) values(1,1, ...);
```

SQLs after rewrite:
```sql
select * from t_order where deleted=0 and id>10 limit 100;
insert into t_order_deleted(id, deleted, ...) values(1,1, ...);
```

Currently, if I want to route to those two tables above, the table `order` must have a column called "deleted".
But in the database, all the data in `order_deleted` is `deleted`, all the data in `order`  is `not deleted`. It means that the "deleted" column is used only for routing.  so ,is it possible to make the rewrite engine remove the `deleted` column in the sql?

In a brief, I just want to use a colum `column_a` to route to target physical table, and meanwhile, I dont want this columns appears in my sql queries.

## Expected Behaviour
Configuration:
```yml
dataSources:
  ds0: ...
shardingRule:  
  tables:
    t_order: 
      actualDataNodes: ds0.t_order, ds0.t_order_deleted
      routing-columns: deleted # those columns will be removed when rewite sql
      tableStrategy: 
        inline:
          shardingColumn: order_id
          algorithmExpression: t_order${deleted==1?'_deleted':''}
```

SQLs before rewrite:
```sql
select * from t_order where deleted=0 and id>10 limit 100
insert into t_order(id, deleted, ...) values(1,1, ...);
```

SQLs after rewrite:
```sql
select * from t_order where id>10 limit 100
insert into t_order_deleted(id,  ...) values(1, ...);
-- The routing column "deleted" is removed, so it wont participating in querying database
```

## Others
I dont know whether the shardingsphere already support that(at least I didnt find it in the doc and any related issues),
