### ISSUE TITLE
The sharding-JDBC non-sharding policy, NoneShardingStrategy, does not work in yml

### ISSUE THREAD

**Issue by devefx** [apache/incubator-shardingsphere#3977]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/incubator-shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?

4.0.0

### Which project did you use? Sharding-JDBC or Sharding-Proxy?

Sharding-JDBC

### Expected behavior

```yml
my_table:
  database-strategy:
    none:
      any: 1
```

```java
public class YamlShardingStrategyConfiguration implements YamlConfiguration {
    
    private YamlStandardShardingStrategyConfiguration standard;
    
    private YamlComplexShardingStrategyConfiguration complex;
    
    private YamlHintShardingStrategyConfiguration hint;
    
    private YamlInlineShardingStrategyConfiguration inline;
    
    private YamlNoneShardingStrategyConfiguration none; // no null
}
```

### Actual behavior

```java
public class YamlShardingStrategyConfiguration implements YamlConfiguration {
    
    private YamlStandardShardingStrategyConfiguration standard;
    
    private YamlComplexShardingStrategyConfiguration complex;
    
    private YamlHintShardingStrategyConfiguration hint;
    
    private YamlInlineShardingStrategyConfiguration inline;
    
    private YamlNoneShardingStrategyConfiguration none; // is null
}
```

### Reason analyze (If you can)

`org.apache.shardingsphere.core.yaml.config.sharding.strategy.YamlNoneShardingStrategyConfiguration`  There must be a field, like `private boolean enabled;`

```yml
my_table:
  database-strategy:
    none:
      enabled: true
```

**Comment by KomachiSion** [comment]
Why do you set sub configure for none strategy?

**Comment by KomachiSion** [comment]
@devefx Can you try to use? 
```yaml
my_table:
  database-strategy:
    none: {}
```

**Comment by devefx** [comment]
> @devefx Can you try to use?
> 
> ```yaml
> my_table:
>   database-strategy:
>     none: {}
> ```

Still not working, a field must be included

**Comment by KomachiSion** [comment]
For my test,

```yaml
my_table:
  database-strategy:
    none: {}
```

This configuration can work. 

Can you provide your full sharding configuration? Or example code?

**Comment by devefx** [comment]
![image](https://user-images.githubusercontent.com/15070360/72433673-d71fc780-37d4-11ea-8ded-29d2b987ea71.png)

**Comment by KomachiSion** [comment]
Sorry, picture is not full configuration and quite inconvenient.
Please paste congfiguration as a text to comment.
You can remove some important data like username,password,url and so on.

**Comment by devefx** [comment]
![image](https://user-images.githubusercontent.com/15070360/72433886-4b5a6b00-37d5-11ea-809f-d2b055a70875.png)

```java
package org.apache.shardingsphere.core.yaml.config.sharding.strategy;

import lombok.Data;

@Data
public final class YamlNoneShardingStrategyConfiguration implements YamlBaseShardingStrategyConfiguration {

    private boolean enabled;
}
```
This is me override

**Comment by devefx** [comment]
This my configuration

```yml
  shardingsphere:
    datasource:
      names: default, marketdata
      default:
        xxxx
      marketdata:
        xxx
    props:
      sql:
        show: true
    sharding:
      default-data-source-name: default
      default-database-strategy:
        standard:
          sharding-column: uid
          precise-algorithm-class-name: my.shardingsphere.strategy.DatabasePreciseShardingAlgorithm
      default-table-strategy:
        standard:
          sharding-column: uid
          precise-algorithm-class-name: my.shardingsphere.strategy.TablePreciseShardingAlgorithm
      tables:
        price_index:
          actual-data-nodes: marketdata.price_index
          database-strategy:
            none: {}
          table-strategy:
            none: {}

```
