### ISSUE TITLE
Will the class Encryptor add two methods contains table and column?

### ISSUE THREAD

**Issue by xiaoma20082008** [apache/incubator-shardingsphere#4382]
Our company use the encrypt for field's encryption and decryption, and we cannot use different aes-token because the class: `AESShardingEncryptor` uses only one key: `aes.key.value` , so we cannot know the aes-token and table's or column's mapping like this:

table | column |  token 
-|-|-
tb1    |    col_1   |    k1  |
tb1    |   col_2   |    k2  |
tb2   |   col_1     |   k3  |

because the class `AESShardingEncryptor` is this:
```java
public final class AESShardingEncryptor implements ShardingEncryptor {
    // ignore other methods
    private byte[] createSecretKey() {
        Preconditions.checkArgument(null != properties.get(AES_KEY), String.format("%s can not be null.", AES_KEY));
        return Arrays.copyOf(DigestUtils.sha1(properties.get(AES_KEY).toString()), 16);
    }
}
```
So I expect the Encryptor class like this class
```java
public interface Encryptor {
    void init();
    String encrypt(String cipherText);
    Object decrypt(String cipherText);
    // add the follow methods
    String encrypt(String table, String column, String cipherText);
    Object decrypt(String table, String column, String cipherText);
}
```
And replaced all the internal method call with it.

Current dependency is : 
```xml
<dependency>
    <groupId>org.apache.shardingsphere</groupId>
    <artifactId>sharding-jdbc-spring-namespace</artifactId>
    <version>4.0.0</version>
</dependency>
```

Or Can you give me another Solution to solve this question?

**Comment by tristaZero** [comment]
@xiaoma20082008 
Hi, what you expected is to use different AESShardingEncryptors for different columns of the same table?

**Comment by xiaoma20082008** [comment]
> @xiaoma20082008
> Hi, what you expected is to use different AESShardingEncryptors for different columns of the same table?
The AESShardingEncryptor interface's methods about encrypt and decrypt should transfer tableName and columnName  just like my code above !

**Comment by tristaZero** [comment]
Hi @xiaoma20082008 
The responsibility of `Encryptor` is only to `encrypt(xxx)` and `decrypt(xxx)`, and there is no need for `Encryptor` to understand what the column and table are. Notice, it is just a `encryptor`.
If you wish to use different `encryptor` with different property `aes.key.value`, you can make good use of configuration, e.g,
```
encryptRule:
  encryptors:
    encryptor_aes1:
      type: aes
      props:
        aes.key.value: 123
    encryptor_aes2:
      type: aes
      props:
        aes.key.value: abc
  tables:
    t_encrypt:
      columns:
        user_id:
          plainColumn: user_plain
          cipherColumn: user_cipher
          encryptor: encryptor_aes1
        order_id:
          cipherColumn: order_cipher
          encryptor: encryptor_aes2
```
