### ISSUE TITLE
sharding-jdbc4，How to configure only tables that need to be fragmented through default config and customized code

### ISSUE THREAD

**Issue by fantacy2001** [apache/incubator-shardingsphere#4431]
Does sharding JDBC support the following? Only the default fragmentation fields and strategy are configured for the databases and tables. The actual data nodes of tables are not configured. The assign tables are obtained through my customized mapping(myself java code). 
I have many modules in my project. Each module only configures tables participating in sharding, and all projects share a common customized sharding rule.
For example：
//my customized mapping(sharding rule)
Map<String,String> shardingMap = new HashMap<>();
        shardingMap.put("tenantId1","db_0:table_01");
        shardingMap.put("tenantId2","db_0:table_02");
        shardingMap.put("tenantId3","db_1:table_03");
        shardingMap.put("tenantId4","db_1:table_04");

//Each module defines its own partition table:
{sku_info,sku_stock……}

How to implement the code? thanks

**Comment by kimmking** [comment]
You wanna "sku_info" literally instead of "table" of "db_0:table_01" in runtime?

**Comment by KomachiSion** [comment]
Hi, @fantacy2001 ,

ShardingSphere need you configured actual data nodes if you want to shard both datasources and tables. If there are no `actualDataNodes` configured, ShardingSphere can't know what's the Possible shardingNodes which should be input into your sharding algorithms.

For your situation, I think you can have a try like follow:

```yaml
dataSources:
  ds_0: !!com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.jdbc.Driver
    jdbcUrl: jdbc:mysql://localhost:3306/demo_ds_0?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password:
  ds_1: !!com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.jdbc.Driver
    jdbcUrl: jdbc:mysql://localhost:3306/demo_ds_1?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password:


shardingRule:
  tables:
    tableA: 
      actualDataNodes: ds_0.tenantId&->{1..2},ds_1.tenantId{3..4}   
    tableB:
      actualDataNodes: ds_0.tenantId&->{1..2},ds_1.tenantId{3..4} 
  defaultDatabaseStrategy:
    stardard:
      shardingColumn: xxx
      preciseShardingAlgorithm: ${your.algorithm}
  defaultTableStrategy:
    stardard:
      shardingColumn: yyy
      preciseShardingAlgorithm: ${your.algorithm}
```

and map the actual tableName in your algorithms.
