### ISSUE TITLE
Is this possible to just shard databases with table rule configuration?

### ISSUE THREAD

**Issue by bharathikannan-zarget** [apache/incubator-shardingsphere#4478]
I am trying to use ShardingSphere in one of my applications.
Is there a way I just shard databases alone without configuring table rule configurations.

Example:
```
For users 1 - 100 => db0, 101-200 => db1 for all the tables.
```

**Comment by kimmking** [comment]
Yes, you shoud config a default database strategy with your above rule,
and  a default table strategy with none.

**Comment by dongzl** [comment]
Hi @bharathikannan-zarget , @kimmking , I understand **default table strategy with none** config only can be used after 5.0.0 version.

reference issue: #4276 .
reference pr: #4369 .

**Comment by kimmking** [comment]
Oh...I will tell Haoran to merge related pr to 4.x.

**Comment by bharathikannan-zarget** [comment]
> Oh...I will tell Haoran to merge related pr to 4.x.

Hi @kimmking , it will be really great if it is part of 4.x. I am using ShardingSphere 4.x with spring boot.

**Comment by kimmking** [comment]
> > Oh...I will tell Haoran to merge related pr to 4.x.
> 
> Hi @kimmking , it will be really great if it is part of 4.x. I am using ShardingSphere 4.x with spring boot.

@menghaoranss

**Comment by bharathikannan-zarget** [comment]
Hi @kimmking @dongzl 

Is it available part of 4.0.1?  Do you have an estimated timeline for release of 4.x and 5.x?

**Comment by menghaoranss** [comment]
> Hi @kimmking @dongzl
> 
> Is it available part of 4.0.1? Do you have an estimated timeline for release of 4.x and 5.x?

@bharathikannan-zarget We will discuss later, in which release version to fix it.

**Comment by bharathikannan-zarget** [comment]
Our production release is pending for this patch. If we know the release timeline, it is easier for us to postpone or think about alternatives. 

Can you guys please help?

**Comment by bharathikannan-zarget** [comment]
@kimmking @dongzl can you guys please help?

**Comment by menghaoranss** [comment]
@bharathikannan-zarget  could you provide a full  sharding rule configurations of your application?
And do you expect the tables in the shard databases to be exactly the same ? just like: 
```
db0.user (0-100)
db1.user(101-200)
```

**Comment by menghaoranss** [comment]
> @bharathikannan-zarget could you provide a full sharding rule configurations of your application?
> And do you expect the tables in the shard databases to be exactly the same ? just like:
> 
> ```
> db0.user (0-100)
> db1.user(101-200)
> ```

I suggest, you can refer to examples/sharding-jdbc-example/other-feature-example/hit-example.

Use hint strategy to achieve only shard databases.

The following configuration may help you:
```
shardingRule:
  tables:
    t_order:
      actualDataNodes: ds_${0..1}.t_order
    t_order_item:
      actualDataNodes: ds_${0..1}.t_order_item
  bindingTables:
    - t_order,t_order_item
  broadcastTables:
    - t_address
  
  defaultDatabaseStrategy:
    hint:
      algorithmClassName: org.apache.shardingsphere.example.hint.raw.jdbc.ModuloHintShardingAlgorithm
  defaultTableStrategy:
    none:
```
then you should implement yourself algorithmClass for your sharding rule of databases.

**Comment by bharathikannan-zarget** [comment]
Hi @menghaoranss 

```
  @Bean
  StandardShardingStrategyConfiguration standardShardingStrategyConfiguration() {
    return new StandardShardingStrategyConfiguration("tenant_id", new TenantIDBasedRoutingAlgorithm());
  }


  class TenantIDBasedRoutingAlgorithm implements PreciseShardingAlgorithm<String> {
    @Override
    public String doSharding(Collection<String> collection,
        PreciseShardingValue<String> preciseShardingValue) {
      System.out.println("Sharding Value::; " + preciseShardingValue.getValue());
      return null;
    }
  }
```

# Sharding Config

```
@Bean
  public DataSource createDataSource() throws SQLException {
    ShardingRuleConfiguration shardingRuleConfiguration = new ShardingRuleConfiguration();
    shardingRuleConfiguration.setDefaultDatabaseShardingStrategyConfig(standardShardingStrategyConfiguration());

    return ShardingDataSourceFactory.createDataSource(getDataSources(), shardingRuleConfiguration, new HashMap<>(), new Properties());
  }
```

We use database level sharding, for all the database same tables will be present. Based on the tenant id, we will route the database accordingly. I used ShardingDatabaseStrategey with no explicit table rules, i want sharding rules applied for the tables.

**Comment by KomachiSion** [comment]
@bharathikannan-zarget , If you do not config tableRule, ShardingSphere can't know tables you input whether need to do shard or not.

So you at least config logicTableName and actualDataNodes like 

```
shardingRule:
  tables:
    t_order:
      actualDataNodes: ds_${0..1}.t_order
    t_order_item:
      actualDataNodes: ds_${0..1}.t_order_item
   ....
```

And then you config your `defaultDatabaseStrategy` will be ok.

**Comment by bharathikannan-zarget** [comment]
@KomachiSion 
Thanks for your response. 

I have 100+ same tables in all my databases. Is that mean, I need to add all the tables in the rule configuration for sharding?

Is there anyway to configure wildcard tables, like i want to do sharding for all the tables in my database based on a column value?. Please correct me if i am wrong.

**Comment by KomachiSion** [comment]
what’s your means about 100+ same tables? Is it that you shard a logicTable to 100+ shard tables?
If so , the `actualDataNodes: ds_${0..1}.t_order_${0..50}` will be ok. 

you can search and learn about the groovy language.

**Comment by bharathikannan-zarget** [comment]
@KomachiSion 

```
db0

Tables:
| account 
| user
| events
| history
| preferences

```

db1

```

Tables:
| account 
| user
| events
| history
| preferences
```

db2
```

Tables:
| account 
| user
| events
| history
| preferences
```

So let's say

```
Rules:

tenant_id < 100 => db0
tenant_id > 100 < 200 => db1
tenant_id > 200 < 300 => db2

Sample Queries:

select * from accounts where tenant_id=10;  => db0

select * from history where tenant_id = 10; => db0

select * from accounts where tenant_id=180; => db1

select * from history where tenant_id = 180; => db1

```

Thanks.

**Comment by KomachiSion** [comment]
@menghaoranss's solution is ok

```
shardingRule:
  tables:
    account:
      actualDataNodes: ds_${0..2}.account
    user:
      actualDataNodes: ds_${0..2}.user
    ....

  defaultDatabaseStrategy:
    inline:
        shardingColumn: tenant_id
        algorithmExpression: ds_${tenant_id / 100}
  defaultTableStrategy:
    none:
```
