### ISSUE TITLE
order by not support string column when cross database query

### ISSUE THREAD

**Issue by xiaoxiong581** [apache/incubator-shardingsphere#4639]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/incubator-shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
4.0.0
### Which project did you use? Sharding-JDBC or Sharding-Proxy?
Sharding-Proxy
### Expected behavior
cross database query support order by use string column, query sql is always executing, cann't get result or error
### Actual behavior
not support, only support when route one database, cross database support i test is int、datetime etc
#### create table sql
```sql
CREATE TABLE t_cluster(
    clusterId VARCHAR(64) NOT NULL   COMMENT '数据库集群ID' ,
    clusterName VARCHAR(128) NOT NULL   COMMENT '数据库集群名称' ,
    projectId VARCHAR(64) NOT NULL   COMMENT '项目ID' ,
    createTime DATETIME NOT NULL   COMMENT '创建时间' ,
    updateTime DATETIME NOT NULL   COMMENT '更新时间' ,
    PRIMARY KEY (clusterId)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT = '数据库集群信息表';
ALTER TABLE t_cluster ADD UNIQUE index_cluster_unique_name(clusterName);
```
#### server.yaml
```yaml
authentication:
  users:
    root:
      password: xxxxx
    migu:
      password: xxxxx
      authorizedSchemas: databasemanager
props:
  sql.show: true
```
#### config-databasemanager.yaml
```yaml
schemaName: databasemanager

dataSources:
  ds_0:
    url: jdbc:mysql://192.168.137.102:3306/databasemanager?serverTimezone=UTC&useSSL=false
    username: root
    password: xxxxx
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
  ds_1:
    url: jdbc:mysql://192.168.137.102:3307/databasemanager?serverTimezone=UTC&useSSL=false
    username: root
    password: xxxx
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50

shardingRule:
  tables:
    t_cluster:
      actualDataNodes: ds_${0..1}.t_cluster
      tableStrategy:
        none:
      databaseStrategy:
        inline:
          shardingColumn: clusterId
          algorithmExpression: ds_${clusterId.hashCode().abs() % 2}
    t_cluster_instance:
      actualDataNodes: ds_${0..1}.t_cluster_instance
      tableStrategy:
        none:
      databaseStrategy:
        inline:
          shardingColumn: clusterId
          algorithmExpression: ds_${clusterId.hashCode().abs() % 2}
  bindingTables:
    - t_cluster,t_cluster_instance
  defaultDatabaseStrategy:
    none:
  defaultTableStrategy:
    none:
```
#### test sql
```sql
select * from t_cluster order by clusterId;
```
