### ISSUE TITLE
Is this UI module available ?

### ISSUE THREAD

**Issue by pkwenda** [apache/incubator-shardingsphere#4921]
## Question

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/incubator-shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

## I tried to start the project，How to use it ?

![image](https://user-images.githubusercontent.com/14212375/77424045-75e72680-6e0b-11ea-890f-3d0c14bff55c.png)

![image](https://user-images.githubusercontent.com/14212375/77424067-7b447100-6e0b-11ea-880f-c07ad149e21b.png)

But I don't know what I'm supposed to fill in, The documentation is not clear , right

Is need me copy the yml configuration above java project  into here ? 

I want to try to start it to understand its process, increase the relevant configuration about `consul` 

but now , i can't know how to  add schem and orther setting

**Comment by pkwenda** [comment]
this label is `UI`.  please

**Comment by pkwenda** [comment]
I have configured zookeeper in Java yml

![image](https://user-images.githubusercontent.com/14212375/77426524-9ca75c00-6e0f-11ea-83fd-834a4eb1f458.png)

in ui project : 

![image](https://user-images.githubusercontent.com/14212375/77426585-be084800-6e0f-11ea-8ccf-823f623479cc.png)

**Comment by kimmking** [comment]
which version?

**Comment by kimmking** [comment]
@menghaoranss will follow this issue.

**Comment by SanmuWangZJU** [comment]
I think you can refer to source code in `sharding-ui-backend` module while filling config in ui.

- for version 4.x, config check/update/load are implement in `org.apache.shardingsphere.ui.servcie.impl`

- `Props` can refer to `org.apache.shardingsphere.ui.util.ConfigurationYamlConverter#loadProperties` , content should like [official guide](https://shardingsphere.apache.org/document/current/en/manual/sharding-proxy/configuration/#proxy-property), **but without the first line `prop:`**

- `Authentication` can refer to `org.apache.shardingsphere.core.yaml.config.common.YamlAuthenticationConfiguration`, content should like [official guide](https://shardingsphere.apache.org/document/current/en/manual/sharding-proxy/configuration/#authentication-1), **but without the first line `authentication:`**
authentications here control your access to proxy rather than backend-mysql

- `Schema` can refer to `org.apache.shardingsphere.ui.servcie.impl.ShardingSchemaServiceImpl#checkRuleConfiguration` you can config encryptor/master-slave only/sharding(also can config master-slave), 

  + following example for datasource config

  ```yaml
  ds0: !!org.apache.shardingsphere.orchestration.yaml.config.YamlDataSourceConfiguration
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    properties:
      url: jdbc:mysql://ip:port/schema
      username: 
      password: 
      maxPoolSize: 
  ```

  + following examples for rule config

  ```yaml
  # master-slave-only
  ms_ds0:
      masterDataSourceName: ds0
      slaveDataSourceNames:
        - ds0_slave
      loadBalanceAlgorithmType: ROUND_ROBIN
  ```

  ```yaml
  # sharding with master-slave
  tables:
    logic_table_name: 
        actualDataNodes: 
        databaseStrategy:
        inline:
          shardingColumn: 
          algorithmExpression: 
      tableStrategy: 
        inline:
          shardingColumn: 
          algorithmExpression: 
  defaultTableStrategy:
    none:

  masterSlaveRules:
    ms_ds0:
      masterDataSourceName: ds0
      slaveDataSourceNames:
        - ds0_slave
      loadBalanceAlgorithmType: ROUND_ROBIN
    ms_ds1:
      masterDataSourceName: ds1
      slaveDataSourceNames: 
        - ds1_slave
      loadBalanceAlgorithmType: ROUND_ROBIN
  ```

**Comment by menghaoranss** [comment]
@pkwenda you can refer to reply from @SanmuWangZJU , and we will add  configuration examples on the UI in subsequent versions.

**Comment by pkwenda** [comment]
I have a question.

Why YamlTableRuleConfiguration.java  not have `defaultKeyGenerator` and `defaultDatabaseStrategy` field ？ 

because I add this yml setting 

```
  tables:
    litemall_electronic_coupon_item:
      actualDataNodes: uat-litemall-$->{0}.litemall_electronic_coupon_item
      databaseStrategy:
        standard:
          shardingColumn: company_id   
          preciseAlgorithmClassName: org.apache.shardingsphere.ui.sharding.DataBaseShardingAlgorithm  
    litemall_coupon_user:
      actualDataNodes: uat-litemall-$->{0}.litemall_coupon_user
      databaseStrategy:
        standard:
          shardingColumn: user_id   
          preciseAlgorithmClassName: org.apache.shardingsphere.ui.sharding.DataBaseShardingAlgorithm  
  bindingTables:
    - litemall_electronic_coupon_item,litemall_coupon_user
  defaultDatabaseStrategy: # 默认分库 company_id
    standard:
      sharding-column: company_id
      preciseAlgorithmClassName: org.linlinjava.litemall.db.sharding.DataBaseShardingAlgorithm
  defaultKeyGenerator:
    type: SNOWFLAKE
    column: id
```
it is wrong

 
![image](https://user-images.githubusercontent.com/14212375/77517427-0f1f4700-6eb7-11ea-9e83-87cc7b1b2aeb.png)



but I write another way is ok （del defaultXXX yml key ）：

```
  tables:
    litemall_electronic_coupon_item:
      actualDataNodes: uat-litemall-$->{0}.litemall_electronic_coupon_item
      databaseStrategy:
        standard:
          shardingColumn: company_id   
          preciseAlgorithmClassName: org.apache.shardingsphere.ui.sharding.DataBaseShardingAlgorithm  
      keyGenerator:
        type: SNOWFLAKE
        column: order_item_id    
    litemall_coupon_user:
      actualDataNodes: uat-litemall-$->{0}.litemall_coupon_user
      databaseStrategy:
        standard:
          shardingColumn: user_id   
          preciseAlgorithmClassName: org.apache.shardingsphere.ui.sharding.DataBaseShardingAlgorithm  
      keyGenerator:
        type: SNOWFLAKE
        column: order_item_id    
  bindingTables:
    - litemall_electronic_coupon_item,litemall_coupon_user

```

Was it designed this way ？ OR BUG ？

IF it is bug , Can I fix it ?
