### ISSUE TITLE
Batch insert via mybatis,useGeneratedKeys not work

### ISSUE THREAD

**Issue by jacknate** [apache/incubator-shardingsphere#5040]
### Which version of ShardingSphere did you use?

* sharding-jdbc-core
  4.0.1

* mybatis-spring-boot-starter

  2.1.2

* mysql-connector-java

  8.0.19

* spring-boot

  2.2.2.RELEASE

### Which project did you use? Sharding-JDBC or Sharding-Proxy?

Sharding-JDBC

### Expected behavior

Using mybatis to batch insert records, write back the auto generated keys(id) to entity's key filed. 

### Actual behavior

Entity's key field is still null.

### Reason analyze (If you can)

after invoke org.apache.shardingsphere.shardingjdbc.jdbc.core.statement.ShardingPreparedStatement#shard
SQLRouteResult.generatedKey is null

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.

* sql to create table:

``` sql
CREATE TABLE `t_user0` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `sharding_key` int(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_bin

CREATE TABLE `t_user1` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `sharding_key` int(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=100000001 DEFAULT CHARSET=utf8 COLLATE=utf8_bin

CREATE TABLE `t_user2` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `sharding_key` int(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=200000001 DEFAULT CHARSET=utf8 COLLATE=utf8_bin

CREATE TABLE `t_user3` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `sharding_key` int(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=300000001 DEFAULT CHARSET=utf8 COLLATE=utf8_bin
```

* sharding config

``` yaml
dataSources:
  ds_0: !!com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://127.0.0.1:3306/test?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    maximumPoolSize: 20

shardingRule:
  tables:
    t_user:
      actualDataNodes: ds_0.t_user${0..3}
      databaseStrategy:
        none:
      tableStrategy:
        inline:
          algorithmExpression: t_user${sharding_key % 4}
          shardingColumn: sharding_key
  bindingTables:
    - t_user
  defaultDataSourceName: ds_0

props:
  sql.show: true
```

* UserDO.java

``` java
@Data
@NoArgsConstructor
public class UserDO implements Serializable {
    private Integer id;

    private String name;

    private Integer shardingKey;

    private static final long serialVersionUID = 1L;

	public UserDO(String name, Integer shardingKey) {
		this.name = name;
		this.shardingKey = shardingKey;
	}
}
```

* UserMapper.java

``` java
@Mapper
public interface UserMapper {
	int batchInsert(List<UserDO> list);
}
```

* UserMapper.xml

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapper PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN" "http://mybatis.org/dtd/mybatis-3-mapper.dtd">
<mapper namespace="com.jack.test.sharding.jdbc.dal.mapper.UserMapper">
  <resultMap id="BaseResultMap" type="com.jack.test.sharding.jdbc.dal.dataobject.UserDO">
    <id column="id" jdbcType="INTEGER" property="id" />
    <result column="name" jdbcType="VARCHAR" property="name" />
    <result column="sharding_key" jdbcType="INTEGER" property="shardingKey" />
  </resultMap>
  <sql id="Base_Column_List">
    id, `name`, sharding_key
  </sql>
    <insert id="batchInsert" keyColumn="id" keyProperty="id" useGeneratedKeys="true">
        insert into t_user (`name`, sharding_key)
        values
        <foreach collection="list" item="item" index="index" separator=",">
            (
            #{item.name,jdbcType=VARCHAR}, #{item.shardingKey,jdbcType=INTEGER}
            )
        </foreach>
    </insert>
</mapper>
```

* DataSourceConfig.java

``` java
@Configuration
public class DataSourceConfig {
	@Bean
	public DataSource dataSource() {
		try {
			String yamlStr = org.apache.commons.io.IOUtils.toString(new ClassPathResource("application-sharding-databases.yml").getInputStream(), StandardCharsets.UTF_8);
			DataSource dataSource = YamlShardingDataSourceFactory.createDataSource(yamlStr.getBytes());
			return dataSource;
		} catch (Exception e) {
			throw new RuntimeException(e);
		}
	}
}
```

* ShardingTest.java

``` java
	@Test
	void batchInsert() {
		List<UserDO> users = IntStream.range(1,101).boxed().map(i->new UserDO("name"+i,i)).collect(Collectors.toList());
		userMapper.batchInsert(users);
		for (UserDO user : users) {
			assertNotNull(user.getId());
		}
	}

```

**Comment by KomachiSion** [comment]
@jacknate , you need to configure keyGenerator for shardingsphere if you want to use generatedKey.

```
shardingRule:
  tables:
    t_user:
      key-generator:
        column: xxx
        type: SNOWFLAKE
```

detail see [document](https://shardingsphere.apache.org/document/current/en/manual/sharding-jdbc/configuration/config-spring-boot/)
