### ISSUE TITLE
Why is there a delay of about 5 seconds service takes effect, when changing the rules of the registration center ?

### ISSUE THREAD

**Issue by cws1981** [apache/incubator-shardingsphere#5198]
Why is there a delay of about 5 seconds when changing the rules of the registration center? I use version 4.0.1 and zk registration center.

**Comment by menghaoranss** [comment]
@cws1981 ,hi, could you describe your specific steps ?

**Comment by kimmking** [comment]
It's due with your config details.

**Comment by kimmking** [comment]
@cws1981 any  more details for profiling? logs, configs ?

**Comment by cws1981** [comment]
> @cws1981 any more details for profiling? logs, configs ?

```
20/04/17 15:47:29 INFO Curator-TreeCache-0 org.apache.shardingsphere.core.config.log.ConfigurationLogger: ShardingRuleConfiguration
tables:
  log_process:
    actualDataNodes: dataSource.log_process,dataSource.log_process_2020_$->{4..12}
    keyGenerator:
      column: id
      type: SNOWFLAKE_SIMPLE
    logicTable: log_process
    tableStrategy:
      standard:
        preciseAlgorithmClassName: com.bolome.base.shardingjdbc.shardingAlgorithm.IDPrecise
        shardingColumn: id

20/04/17 15:47:29 INFO Curator-TreeCache-0 org.apache.shardingsphere.core.config.log.ConfigurationLogger: Properties
sql.show: 'false'


20/04/17 15:47:56 ERROR http-bio-8080-exec-1 com.bolome.pms.advisor.ExceptionControllerAdvice: 
### Error querying database.  Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'pms_stage.log_process_2020_1' doesn't exist
### The error may exist in class path resource [com/bolome/pms/shardingMappers/log/LogProcessMapper.xml]
### The error may involve com.bolome.pms.shardingDao.log.LogProcessMapper.selectByExample-Inline

```

Time to see the log I modified the configuration at 15:47:29, but the report does not exist at 15:47:56
